// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: get_offer_package.proto

package com.mservice.fs.onboarding.model.notipackage.protomodel;

public final class GetOfferPackage {
  private GetOfferPackage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetOfferPackageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetOfferPackageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OfferPackage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OfferPackage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027get_offer_package.proto\"\236\005\n\027GetOfferPa" +
      "ckageResponse\022\022\n\nrequest_id\030\001 \001(\t\022\020\n\010age" +
      "nt_id\030\002 \001(\003\022+\n\021loan_product_code\030\003 \001(\0162\020" +
      ".LoanProductCode\022\030\n\020response_message\030\004 \001" +
      "(\t\022\032\n\022response_timestamp\030\005 \001(\003\022$\n\rproduc" +
      "t_group\030\006 \001(\0162\r.ProductGroup\022\022\n\nproduct_" +
      "id\030\007 \001(\t\022\023\n\013merchant_id\030\010 \001(\t\022%\n\016offer_p" +
      "ackages\030\t \003(\0132\r.OfferPackage\022\032\n\tlender_i" +
      "d\030\n \001(\0162\007.Lender\022\027\n\017kyc_update_time\030\013 \001(" +
      "\t\022\020\n\010kyc_flag\030\014 \001(\010\022\031\n\021momo_credit_score" +
      "\030\r \001(\001\022\"\n\014segment_user\030\016 \001(\0162\014.SegmentUs" +
      "er\022-\n\022offer_package_type\030\017 \001(\0162\021.OfferPa" +
      "ckageType\022\025\n\rresponse_code\030\020 \001(\005\022\030\n\020momo" +
      "_loan_app_id\030\021 \001(\t\022\025\n\rmodel_version\030\022 \001(" +
      "\t\022\035\n\014lender_logic\030\023 \001(\0162\007.Lender\022\026\n\016app_" +
      "session_id\030\024 \001(\t\022$\n\rmerchant_type\030\025 \001(\0162" +
      "\r.MerchantType\022\026\n\016experiment_tag\030\026 \001(\t\022\022" +
      "\n\noffer_rule\030\027 \003(\t\"\373\003\n\014OfferPackage\022\025\n\rp" +
      "ackage_group\030\001 \001(\t\022\024\n\014package_name\030\002 \001(\t" +
      "\022\024\n\014package_code\030\003 \001(\t\022\032\n\tlender_id\030\004 \001(" +
      "\0162\007.Lender\022\014\n\004rank\030\005 \001(\005\022\026\n\016package_amou" +
      "nt\030\006 \001(\005\022\026\n\016package_status\030\007 \001(\t\022\024\n\014pack" +
      "age_type\030\010 \001(\t\022\026\n\016classification\030\t \001(\t\022\r" +
      "\n\005tenor\030\n \001(\003\022\025\n\rinterest_rate\030\013 \001(\001\022\027\n\017" +
      "interest_amount\030\014 \001(\002\022\030\n\020disbursed_amoun" +
      "t\030\r \001(\002\022\026\n\016payment_amount\030\016 \001(\002\022\027\n\017min_l" +
      "oan_amount\030\017 \001(\002\022\027\n\017max_loan_amount\030\020 \001(" +
      "\002\022\023\n\013service_fee\030\021 \001(\002\022\026\n\016collection_fee" +
      "\030\022 \001(\002\022\025\n\rdisbursed_fee\030\023 \001(\002\022\032\n\022late_in" +
      "terest_rate\030\024 \001(\001\022\020\n\010late_fee\030\025 \001(\002\022\013\n\003e" +
      "mi\030\026 \001(\002*\375\001\n\017LoanProductCode\022\030\n\024UNKNOWN_" +
      "PRODUCT_CODE\020\000\022\031\n\025FINANCE_LENDING_EVNFC\020" +
      "\001\022\024\n\020PAYLATER_LENDING\020\002\022\030\n\024PAYLATER_CRED" +
      "IT_CARD\020\003\022\023\n\017PAYLATER_NEWTON\020\004\022\023\n\017PAYLAT" +
      "ER_BUYNOW\020\005\022\030\n\024CASH_LOAN_FMOB_AMBER\020\006\022\027\n" +
      "\023CASHLOAN_FMFB_AMBER\020\007\022\017\n\013ALL_PRODUCT\020\010\022" +
      "\027\n\023LENDING_MARKETPLACE\020\t*\345\001\n\006Lender\022\022\n\016U" +
      "NKNOWN_LENDER\020\000\022\016\n\nALL_LENDER\020\001\022\013\n\007TP_BA" +
      "NK\020\002\022\t\n\005AMBER\020\003\022\010\n\004FLIK\020\004\022\013\n\007MCREDIT\020\005\022\007" +
      "\n\003BVB\020\006\022\007\n\003VIB\020\007\022\007\n\003ACB\020\010\022\007\n\003MBB\020\t\022\017\n\013MO" +
      "MO_LENDER\020\n\022\017\n\013HOME_CREDIT\020\013\022\007\n\003OCB\020\014\022\007\n" +
      "\003OJB\020\r\022\007\n\003VCB\020\016\022\017\n\013VIET_CREDIT\020\017\022\r\n\tFE_C" +
      "REDIT\020\020\022\007\n\003MBV\020\021*p\n\014MerchantType\022\031\n\025UNKN" +
      "OWN_MERCHANT_TYPE\020\000\022!\n\035MERCHANT_TYPE_ONL" +
      "INE_BUSINESS\020\001\022\"\n\036MERCHANT_TYPE_OFFLINE_" +
      "BUSINESS\020\002*\235\001\n\020OfferPackageType\022\036\n\032UNKNO" +
      "WN_OFFER_PACKAGE_TYPE\020\000\022\025\n\021PREAPPROVAL_O" +
      "FFER\020\001\022\020\n\014NORMAL_OFFER\020\002\022\021\n\rSPECIAL_OFFE" +
      "R\020\003\022\010\n\004OB30\020\004\022\r\n\tOB30_PLUS\020\005\022\t\n\005OB100\020\006\022" +
      "\t\n\005GEN_Z\020\007*\341\002\n\013SegmentUser\022\035\n\031UNKNOWN_LO" +
      "AN_SEGMENT_TYPE\020\000\022\007\n\003NEW\020\001\022\014\n\010REPEATED\020\002" +
      "\022\024\n\020QUICK_ACTIVATION\020\003\022\030\n\024FAST_MONEY_PIL" +
      "OT_EXP\020\004\022\021\n\rBNPL_EXP_RULE\020\005\022\023\n\017NEWTON_EX" +
      "P_RULE\020\006\022\036\n\032NEWTON_FORCE_MANUAL_REVIEW\020\007" +
      "\022\n\n\006RELOAN\020\010\022\014\n\010EXP_RULE\020\t\022\017\n\013PILOT_GEN_" +
      "Z\020\n\022\025\n\021HARRISON_EXP_RULE\020\013\022\027\n\023CHECK_KLP_" +
      "PRE_SCORE\020\014\022\r\n\tTHIN_FILE\020\r\022\020\n\014GENZ_STUDE" +
      "NT\020\016\022\023\n\017HOME_CREDIT_ACL\020\017\022\023\n\017HOME_CREDIT" +
      "_CLX\020\020*V\n\014ProductGroup\022\031\n\025UNKNOWN_PRODUC" +
      "T_GROUP\020\000\022\r\n\tCASH_LOAN\020\001\022\014\n\010PAYLATER\020\002\022\016" +
      "\n\nOVER_DRAFT\020\003B;\n7com.mservice.fs.onboar" +
      "ding.model.notipackage.protomodelP\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GetOfferPackageResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetOfferPackageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetOfferPackageResponse_descriptor,
        new java.lang.String[] { "RequestId", "AgentId", "LoanProductCode", "ResponseMessage", "ResponseTimestamp", "ProductGroup", "ProductId", "MerchantId", "OfferPackages", "LenderId", "KycUpdateTime", "KycFlag", "MomoCreditScore", "SegmentUser", "OfferPackageType", "ResponseCode", "MomoLoanAppId", "ModelVersion", "LenderLogic", "AppSessionId", "MerchantType", "ExperimentTag", "OfferRule", });
    internal_static_OfferPackage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_OfferPackage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OfferPackage_descriptor,
        new java.lang.String[] { "PackageGroup", "PackageName", "PackageCode", "LenderId", "Rank", "PackageAmount", "PackageStatus", "PackageType", "Classification", "Tenor", "InterestRate", "InterestAmount", "DisbursedAmount", "PaymentAmount", "MinLoanAmount", "MaxLoanAmount", "ServiceFee", "CollectionFee", "DisbursedFee", "LateInterestRate", "LateFee", "Emi", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
