// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetOfferPackageResponse

package com.mservice.fs.onboarding.model.notipackage.protomodel;

public final class GetOfferPackageResponseOuterClass {
  private GetOfferPackageResponseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetOfferPackageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetOfferPackageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OfferPackage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OfferPackage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\027GetOfferPackageResponse\"\220\004\n\027GetOfferPa" +
      "ckageResponse\022\022\n\nrequest_id\030\001 \001(\t\022\020\n\010age" +
      "nt_id\030\002 \001(\003\022+\n\021loan_product_code\030\003 \001(\0162\020" +
      ".LoanProductCode\022*\n\020response_message\030\004 \001" +
      "(\0162\020.ResponseMessage\022\032\n\022response_timesta" +
      "mp\030\005 \001(\003\022$\n\rproduct_group\030\006 \001(\0162\r.Produc" +
      "tGroup\022\022\n\nproduct_id\030\007 \001(\t\022\023\n\013merchant_i" +
      "d\030\010 \001(\t\022%\n\016offer_packages\030\t \001(\0132\r.OfferP" +
      "ackage\022\032\n\tlender_id\030\n \001(\0162\007.Lender\022\027\n\017ky" +
      "c_update_time\030\013 \001(\t\022\020\n\010kyc_flag\030\014 \001(\010\022\031\n" +
      "\021momo_credit_score\030\r \001(\001\022\"\n\014segment_user" +
      "\030\016 \001(\0162\014.SegmentUser\022-\n\022offer_package_ty" +
      "pe\030\017 \001(\0162\021.OfferPackageType\022\025\n\rresponse_" +
      "code\030\020 \001(\005\022\030\n\020momo_loan_app_id\030\021 \001(\t\"\223\001\n" +
      "\014OfferPackage\022\025\n\rpackage_group\030\001 \001(\t\022\024\n\014" +
      "package_name\030\002 \001(\t\022\024\n\014package_code\030\003 \001(\t" +
      "\022\032\n\tlender_id\030\004 \001(\0162\007.Lender\022\014\n\004rank\030\005 \001" +
      "(\005\022\026\n\016package_amount\030\006 \001(\005*m\n\006Lender\022\022\n\016" +
      "UNKNOWN_LENDER\020\000\022\016\n\nALL_LENDER\020\001\022\013\n\007TP_B" +
      "ANK\020\002\022\t\n\005AMBER\020\003\022\010\n\004FLIK\020\004\022\013\n\007MCREDIT\020\005\022" +
      "\007\n\003BVB\020\006\022\007\n\003VIB\020\007*\344\001\n\017LoanProductCode\022\030\n" +
      "\024UNKNOWN_PRODUCT_CODE\020\000\022\031\n\025FINANCE_LENDI" +
      "NG_EVNFC\020\001\022\024\n\020PAYLATER_LENDING\020\002\022\030\n\024PAYL" +
      "ATER_CREDIT_CARD\020\003\022\023\n\017PAYLATER_NEWTON\020\004\022" +
      "\023\n\017PAYLATER_BUYNOW\020\005\022\030\n\024CASH_LOAN_FMOB_A" +
      "MBER\020\006\022\027\n\023CASHLOAN_FMFB_AMBER\020\007\022\017\n\013ALL_P" +
      "RODUCT\020\010*\250\001\n\017ResponseMessage\022\023\n\017UNKNOWN_" +
      "MESSAGE\020\000\022\024\n\020SUCCESS_RESPONSE\020\001\022\022\n\016INFO_" +
      "NOT_FOUND\020\002\022\022\n\016ERROR_RESPONSE\020\003\022\017\n\013SUCCE" +
      "SS_EXT\020\004\022\r\n\tERROR_EXT\020\005\022\020\n\014TIME_OUT_EXT\020" +
      "\006\022\020\n\014TIME_OUT_INT\020\007*\367\001\n\013SegmentUser\022\035\n\031U" +
      "NKNOWN_LOAN_SEGMENT_TYPE\020\000\022\007\n\003NEW\020\001\022\014\n\010R" +
      "EPEATED\020\002\022\024\n\020QUICK_ACTIVATION\020\003\022\030\n\024FAST_" +
      "MONEY_PILOT_EXP\020\004\022\021\n\rBNPL_EXP_RULE\020\005\022\023\n\017" +
      "NEWTON_EXP_RULE\020\006\022\036\n\032NEWTON_FORCE_MANUAL" +
      "_REVIEW\020\007\022\020\n\014SEGMENT_OB30\020\010\022\025\n\021SEGMENT_O" +
      "B30_PLUS\020\t\022\021\n\rSEGMENT_OB100\020\n*V\n\014Product" +
      "Group\022\031\n\025UNKNOWN_PRODUCT_GROUP\020\000\022\r\n\tCASH" +
      "_LOAN\020\001\022\014\n\010PAYLATER\020\002\022\016\n\nOVER_DRAFT\020\003*\235\001" +
      "\n\020OfferPackageType\022\036\n\032UNKNOWN_OFFER_PACK" +
      "AGE_TYPE\020\000\022\025\n\021PREAPPROVAL_OFFER\020\001\022\020\n\014NOR" +
      "MAL_OFFER\020\002\022\021\n\rSPECIAL_OFFER\020\003\022\010\n\004OB30\020\004" +
      "\022\r\n\tOB30_PLUS\020\005\022\t\n\005OB100\020\006\022\t\n\005GEN_Z\020\007B;\n" +
      "7com.mservice.fs.onboarding.model.notipa" +
      "ckage.protomodelP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GetOfferPackageResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetOfferPackageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetOfferPackageResponse_descriptor,
        new String[] { "RequestId", "AgentId", "LoanProductCode", "ResponseMessage", "ResponseTimestamp", "ProductGroup", "ProductId", "MerchantId", "OfferPackages", "LenderId", "KycUpdateTime", "KycFlag", "MomoCreditScore", "SegmentUser", "OfferPackageType", "ResponseCode", "MomoLoanAppId", });
    internal_static_OfferPackage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_OfferPackage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OfferPackage_descriptor,
        new String[] { "PackageGroup", "PackageName", "PackageCode", "LenderId", "Rank", "PackageAmount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
