// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: get_offer_package.proto

package com.mservice.fs.onboarding.model.notipackage.protomodel;

public interface GetOfferPackageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetOfferPackageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * unique id for each request
   * </pre>
   *
   * <code>string request_id = 1;</code>
   * @return The requestId.
   */
  java.lang.String getRequestId();
  /**
   * <pre>
   * unique id for each request
   * </pre>
   *
   * <code>string request_id = 1;</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <pre>
   * Momo unique agentId for each Momo user
   * </pre>
   *
   * <code>int64 agent_id = 2;</code>
   * @return The agentId.
   */
  long getAgentId();

  /**
   * <pre>
   * each branch maps to a particular code
   * </pre>
   *
   * <code>.LoanProductCode loan_product_code = 3;</code>
   * @return The enum numeric value on the wire for loanProductCode.
   */
  int getLoanProductCodeValue();
  /**
   * <pre>
   * each branch maps to a particular code
   * </pre>
   *
   * <code>.LoanProductCode loan_product_code = 3;</code>
   * @return The loanProductCode.
   */
  com.mservice.fs.onboarding.model.notipackage.protomodel.LoanProductCode getLoanProductCode();

  /**
   * <pre>
   * the result of the request
   * </pre>
   *
   * <code>string response_message = 4;</code>
   * @return The responseMessage.
   */
  java.lang.String getResponseMessage();
  /**
   * <pre>
   * the result of the request
   * </pre>
   *
   * <code>string response_message = 4;</code>
   * @return The bytes for responseMessage.
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();

  /**
   * <pre>
   * unix timestamp in milliseconds
   * </pre>
   *
   * <code>int64 response_timestamp = 5;</code>
   * @return The responseTimestamp.
   */
  long getResponseTimestamp();

  /**
   * <pre>
   * a group of the Lending business
   * </pre>
   *
   * <code>.ProductGroup product_group = 6;</code>
   * @return The enum numeric value on the wire for productGroup.
   */
  int getProductGroupValue();
  /**
   * <pre>
   * a group of the Lending business
   * </pre>
   *
   * <code>.ProductGroup product_group = 6;</code>
   * @return The productGroup.
   */
  com.mservice.fs.onboarding.model.notipackage.protomodel.ProductGroup getProductGroup();

  /**
   * <pre>
   * a unique ID for each product
   * </pre>
   *
   * <code>string product_id = 7;</code>
   * @return The productId.
   */
  java.lang.String getProductId();
  /**
   * <pre>
   * a unique ID for each product
   * </pre>
   *
   * <code>string product_id = 7;</code>
   * @return The bytes for productId.
   */
  com.google.protobuf.ByteString
      getProductIdBytes();

  /**
   * <pre>
   * an ID for each merchant
   * </pre>
   *
   * <code>string merchant_id = 8;</code>
   * @return The merchantId.
   */
  java.lang.String getMerchantId();
  /**
   * <pre>
   * an ID for each merchant
   * </pre>
   *
   * <code>string merchant_id = 8;</code>
   * @return The bytes for merchantId.
   */
  com.google.protobuf.ByteString
      getMerchantIdBytes();

  /**
   * <pre>
   * Offer info for Momo user
   * </pre>
   *
   * <code>repeated .OfferPackage offer_packages = 9;</code>
   */
  java.util.List<com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage> 
      getOfferPackagesList();
  /**
   * <pre>
   * Offer info for Momo user
   * </pre>
   *
   * <code>repeated .OfferPackage offer_packages = 9;</code>
   */
  com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage getOfferPackages(int index);
  /**
   * <pre>
   * Offer info for Momo user
   * </pre>
   *
   * <code>repeated .OfferPackage offer_packages = 9;</code>
   */
  int getOfferPackagesCount();
  /**
   * <pre>
   * Offer info for Momo user
   * </pre>
   *
   * <code>repeated .OfferPackage offer_packages = 9;</code>
   */
  java.util.List<? extends com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackageOrBuilder> 
      getOfferPackagesOrBuilderList();
  /**
   * <pre>
   * Offer info for Momo user
   * </pre>
   *
   * <code>repeated .OfferPackage offer_packages = 9;</code>
   */
  com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackageOrBuilder getOfferPackagesOrBuilder(
      int index);

  /**
   * <pre>
   * lender id
   * </pre>
   *
   * <code>.Lender lender_id = 10;</code>
   * @return The enum numeric value on the wire for lenderId.
   */
  int getLenderIdValue();
  /**
   * <pre>
   * lender id
   * </pre>
   *
   * <code>.Lender lender_id = 10;</code>
   * @return The lenderId.
   */
  com.mservice.fs.onboarding.model.notipackage.protomodel.Lender getLenderId();

  /**
   * <pre>
   * the latest kyc update time
   * </pre>
   *
   * <code>string kyc_update_time = 11;</code>
   * @return The kycUpdateTime.
   */
  java.lang.String getKycUpdateTime();
  /**
   * <pre>
   * the latest kyc update time
   * </pre>
   *
   * <code>string kyc_update_time = 11;</code>
   * @return The bytes for kycUpdateTime.
   */
  com.google.protobuf.ByteString
      getKycUpdateTimeBytes();

  /**
   * <pre>
   * high risk kyc
   * </pre>
   *
   * <code>bool kyc_flag = 12;</code>
   * @return The kycFlag.
   */
  boolean getKycFlag();

  /**
   * <pre>
   * MoMo credit score of user
   * </pre>
   *
   * <code>double momo_credit_score = 13;</code>
   * @return The momoCreditScore.
   */
  double getMomoCreditScore();

  /**
   * <pre>
   * type of user
   * </pre>
   *
   * <code>.SegmentUser segment_user = 14;</code>
   * @return The enum numeric value on the wire for segmentUser.
   */
  int getSegmentUserValue();
  /**
   * <pre>
   * type of user
   * </pre>
   *
   * <code>.SegmentUser segment_user = 14;</code>
   * @return The segmentUser.
   */
  com.mservice.fs.onboarding.model.notipackage.protomodel.SegmentUser getSegmentUser();

  /**
   * <pre>
   * type of Offer
   * </pre>
   *
   * <code>.OfferPackageType offer_package_type = 15;</code>
   * @return The enum numeric value on the wire for offerPackageType.
   */
  int getOfferPackageTypeValue();
  /**
   * <pre>
   * type of Offer
   * </pre>
   *
   * <code>.OfferPackageType offer_package_type = 15;</code>
   * @return The offerPackageType.
   */
  com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackageType getOfferPackageType();

  /**
   * <pre>
   * response code
   * </pre>
   *
   * <code>int32 response_code = 16;</code>
   * @return The responseCode.
   */
  int getResponseCode();

  /**
   * <pre>
   * loan id
   * </pre>
   *
   * <code>string momo_loan_app_id = 17;</code>
   * @return The momoLoanAppId.
   */
  java.lang.String getMomoLoanAppId();
  /**
   * <pre>
   * loan id
   * </pre>
   *
   * <code>string momo_loan_app_id = 17;</code>
   * @return The bytes for momoLoanAppId.
   */
  com.google.protobuf.ByteString
      getMomoLoanAppIdBytes();

  /**
   * <pre>
   * model version
   * </pre>
   *
   * <code>string model_version = 18;</code>
   * @return The modelVersion.
   */
  java.lang.String getModelVersion();
  /**
   * <pre>
   * model version
   * </pre>
   *
   * <code>string model_version = 18;</code>
   * @return The bytes for modelVersion.
   */
  com.google.protobuf.ByteString
      getModelVersionBytes();

  /**
   * <pre>
   * lender logic
   * </pre>
   *
   * <code>.Lender lender_logic = 19;</code>
   * @return The enum numeric value on the wire for lenderLogic.
   */
  int getLenderLogicValue();
  /**
   * <pre>
   * lender logic
   * </pre>
   *
   * <code>.Lender lender_logic = 19;</code>
   * @return The lenderLogic.
   */
  com.mservice.fs.onboarding.model.notipackage.protomodel.Lender getLenderLogic();

  /**
   * <pre>
   * App session id from App
   * </pre>
   *
   * <code>string app_session_id = 20;</code>
   * @return The appSessionId.
   */
  java.lang.String getAppSessionId();
  /**
   * <pre>
   * App session id from App
   * </pre>
   *
   * <code>string app_session_id = 20;</code>
   * @return The bytes for appSessionId.
   */
  com.google.protobuf.ByteString
      getAppSessionIdBytes();

  /**
   * <pre>
   * type of user
   * </pre>
   *
   * <code>.MerchantType merchant_type = 21;</code>
   * @return The enum numeric value on the wire for merchantType.
   */
  int getMerchantTypeValue();
  /**
   * <pre>
   * type of user
   * </pre>
   *
   * <code>.MerchantType merchant_type = 21;</code>
   * @return The merchantType.
   */
  com.mservice.fs.onboarding.model.notipackage.protomodel.MerchantType getMerchantType();

  /**
   * <pre>
   * type of user
   * </pre>
   *
   * <code>string experiment_tag = 22;</code>
   * @return The experimentTag.
   */
  java.lang.String getExperimentTag();
  /**
   * <pre>
   * type of user
   * </pre>
   *
   * <code>string experiment_tag = 22;</code>
   * @return The bytes for experimentTag.
   */
  com.google.protobuf.ByteString
      getExperimentTagBytes();

  /**
   * <pre>
   * List of rules to explain the offer result
   * </pre>
   *
   * <code>repeated string offer_rule = 23;</code>
   * @return A list containing the offerRule.
   */
  java.util.List<java.lang.String>
      getOfferRuleList();
  /**
   * <pre>
   * List of rules to explain the offer result
   * </pre>
   *
   * <code>repeated string offer_rule = 23;</code>
   * @return The count of offerRule.
   */
  int getOfferRuleCount();
  /**
   * <pre>
   * List of rules to explain the offer result
   * </pre>
   *
   * <code>repeated string offer_rule = 23;</code>
   * @param index The index of the element to return.
   * @return The offerRule at the given index.
   */
  java.lang.String getOfferRule(int index);
  /**
   * <pre>
   * List of rules to explain the offer result
   * </pre>
   *
   * <code>repeated string offer_rule = 23;</code>
   * @param index The index of the value to return.
   * @return The bytes of the offerRule at the given index.
   */
  com.google.protobuf.ByteString
      getOfferRuleBytes(int index);
}
