// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: get_offer_package.proto

package com.mservice.fs.onboarding.model.notipackage.protomodel;

/**
 * Protobuf enum {@code Lender}
 */
public enum Lender
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * default unknown lender
   * </pre>
   *
   * <code>UNKNOWN_LENDER = 0;</code>
   */
  UNKNOWN_LENDER(0),
  /**
   * <pre>
   * all lender
   * </pre>
   *
   * <code>ALL_LENDER = 1;</code>
   */
  ALL_LENDER(1),
  /**
   * <pre>
   * TP Bank lender
   * </pre>
   *
   * <code>TP_BANK = 2;</code>
   */
  TP_BANK(2),
  /**
   * <pre>
   * Amber lender
   * </pre>
   *
   * <code>AMBER = 3;</code>
   */
  AMBER(3),
  /**
   * <pre>
   * Flik lender
   * </pre>
   *
   * <code>FLIK = 4;</code>
   */
  FLIK(4),
  /**
   * <pre>
   * MCREDIT
   * </pre>
   *
   * <code>MCREDIT = 5;</code>
   */
  MCREDIT(5),
  /**
   * <pre>
   * Ban Viet Bank
   * </pre>
   *
   * <code>BVB = 6;</code>
   */
  BVB(6),
  /**
   * <pre>
   * VietNam International Bank
   * </pre>
   *
   * <code>VIB = 7;</code>
   */
  VIB(7),
  /**
   * <pre>
   * ASIA COMMERCIAL JOINT STOCK BANK
   * </pre>
   *
   * <code>ACB = 8;</code>
   */
  ACB(8),
  /**
   * <pre>
   * MB Bank
   * </pre>
   *
   * <code>MBB = 9;</code>
   */
  MBB(9),
  /**
   * <pre>
   * MOMO LENDER
   * </pre>
   *
   * <code>MOMO_LENDER = 10;</code>
   */
  MOMO_LENDER(10),
  /**
   * <pre>
   * HOME_CREDIT
   * </pre>
   *
   * <code>HOME_CREDIT = 11;</code>
   */
  HOME_CREDIT(11),
  /**
   * <pre>
   * OCB - Ngan hang Phuong Dong
   * </pre>
   *
   * <code>OCB = 12;</code>
   */
  OCB(12),
  /**
   * <pre>
   * OceanBank - Ngan hang Dai Duong
   * </pre>
   *
   * <code>OJB = 13;</code>
   */
  OJB(13),
  /**
   * <pre>
   * VietcomBank - NH TMCP Ngoai Thuong VN
   * </pre>
   *
   * <code>VCB = 14;</code>
   */
  VCB(14),
  /**
   * <pre>
   * VIET CREDIT
   * </pre>
   *
   * <code>VIET_CREDIT = 15;</code>
   */
  VIET_CREDIT(15),
  /**
   * <pre>
   * FE
   * </pre>
   *
   * <code>FE_CREDIT = 16;</code>
   */
  FE_CREDIT(16),
  /**
   * <pre>
   * MBV
   * </pre>
   *
   * <code>MBV = 17;</code>
   */
  MBV(17),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * default unknown lender
   * </pre>
   *
   * <code>UNKNOWN_LENDER = 0;</code>
   */
  public static final int UNKNOWN_LENDER_VALUE = 0;
  /**
   * <pre>
   * all lender
   * </pre>
   *
   * <code>ALL_LENDER = 1;</code>
   */
  public static final int ALL_LENDER_VALUE = 1;
  /**
   * <pre>
   * TP Bank lender
   * </pre>
   *
   * <code>TP_BANK = 2;</code>
   */
  public static final int TP_BANK_VALUE = 2;
  /**
   * <pre>
   * Amber lender
   * </pre>
   *
   * <code>AMBER = 3;</code>
   */
  public static final int AMBER_VALUE = 3;
  /**
   * <pre>
   * Flik lender
   * </pre>
   *
   * <code>FLIK = 4;</code>
   */
  public static final int FLIK_VALUE = 4;
  /**
   * <pre>
   * MCREDIT
   * </pre>
   *
   * <code>MCREDIT = 5;</code>
   */
  public static final int MCREDIT_VALUE = 5;
  /**
   * <pre>
   * Ban Viet Bank
   * </pre>
   *
   * <code>BVB = 6;</code>
   */
  public static final int BVB_VALUE = 6;
  /**
   * <pre>
   * VietNam International Bank
   * </pre>
   *
   * <code>VIB = 7;</code>
   */
  public static final int VIB_VALUE = 7;
  /**
   * <pre>
   * ASIA COMMERCIAL JOINT STOCK BANK
   * </pre>
   *
   * <code>ACB = 8;</code>
   */
  public static final int ACB_VALUE = 8;
  /**
   * <pre>
   * MB Bank
   * </pre>
   *
   * <code>MBB = 9;</code>
   */
  public static final int MBB_VALUE = 9;
  /**
   * <pre>
   * MOMO LENDER
   * </pre>
   *
   * <code>MOMO_LENDER = 10;</code>
   */
  public static final int MOMO_LENDER_VALUE = 10;
  /**
   * <pre>
   * HOME_CREDIT
   * </pre>
   *
   * <code>HOME_CREDIT = 11;</code>
   */
  public static final int HOME_CREDIT_VALUE = 11;
  /**
   * <pre>
   * OCB - Ngan hang Phuong Dong
   * </pre>
   *
   * <code>OCB = 12;</code>
   */
  public static final int OCB_VALUE = 12;
  /**
   * <pre>
   * OceanBank - Ngan hang Dai Duong
   * </pre>
   *
   * <code>OJB = 13;</code>
   */
  public static final int OJB_VALUE = 13;
  /**
   * <pre>
   * VietcomBank - NH TMCP Ngoai Thuong VN
   * </pre>
   *
   * <code>VCB = 14;</code>
   */
  public static final int VCB_VALUE = 14;
  /**
   * <pre>
   * VIET CREDIT
   * </pre>
   *
   * <code>VIET_CREDIT = 15;</code>
   */
  public static final int VIET_CREDIT_VALUE = 15;
  /**
   * <pre>
   * FE
   * </pre>
   *
   * <code>FE_CREDIT = 16;</code>
   */
  public static final int FE_CREDIT_VALUE = 16;
  /**
   * <pre>
   * MBV
   * </pre>
   *
   * <code>MBV = 17;</code>
   */
  public static final int MBV_VALUE = 17;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Lender valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Lender forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN_LENDER;
      case 1: return ALL_LENDER;
      case 2: return TP_BANK;
      case 3: return AMBER;
      case 4: return FLIK;
      case 5: return MCREDIT;
      case 6: return BVB;
      case 7: return VIB;
      case 8: return ACB;
      case 9: return MBB;
      case 10: return MOMO_LENDER;
      case 11: return HOME_CREDIT;
      case 12: return OCB;
      case 13: return OJB;
      case 14: return VCB;
      case 15: return VIET_CREDIT;
      case 16: return FE_CREDIT;
      case 17: return MBV;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Lender>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Lender> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Lender>() {
          public Lender findValueByNumber(int number) {
            return Lender.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.mservice.fs.onboarding.model.notipackage.protomodel.GetOfferPackage.getDescriptor().getEnumTypes().get(1);
  }

  private static final Lender[] VALUES = values();

  public static Lender valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Lender(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:Lender)
}

