// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: get_offer_package.proto

package com.mservice.fs.onboarding.model.notipackage.protomodel;

/**
 * Protobuf enum {@code LoanProductCode}
 */
public enum LoanProductCode
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOWN_PRODUCT_CODE = 0;</code>
   */
  UNKNOWN_PRODUCT_CODE(0),
  /**
   * <code>FINANCE_LENDING_EVNFC = 1;</code>
   */
  FINANCE_LENDING_EVNFC(1),
  /**
   * <code>PAYLATER_LENDING = 2;</code>
   */
  PAYLATER_LENDING(2),
  /**
   * <code>PAYLATER_CREDIT_CARD = 3;</code>
   */
  PAYLATER_CREDIT_CARD(3),
  /**
   * <code>PAYLATER_NEWTON = 4;</code>
   */
  PAYLATER_NEWTON(4),
  /**
   * <code>PAYLATER_BUYNOW = 5;</code>
   */
  PAYLATER_BUYNOW(5),
  /**
   * <code>CASH_LOAN_FMOB_AMBER = 6;</code>
   */
  CASH_LOAN_FMOB_AMBER(6),
  /**
   * <code>CASHLOAN_FMFB_AMBER = 7;</code>
   */
  CASHLOAN_FMFB_AMBER(7),
  /**
   * <code>ALL_PRODUCT = 8;</code>
   */
  ALL_PRODUCT(8),
  /**
   * <code>LENDING_MARKETPLACE = 9;</code>
   */
  LENDING_MARKETPLACE(9),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNKNOWN_PRODUCT_CODE = 0;</code>
   */
  public static final int UNKNOWN_PRODUCT_CODE_VALUE = 0;
  /**
   * <code>FINANCE_LENDING_EVNFC = 1;</code>
   */
  public static final int FINANCE_LENDING_EVNFC_VALUE = 1;
  /**
   * <code>PAYLATER_LENDING = 2;</code>
   */
  public static final int PAYLATER_LENDING_VALUE = 2;
  /**
   * <code>PAYLATER_CREDIT_CARD = 3;</code>
   */
  public static final int PAYLATER_CREDIT_CARD_VALUE = 3;
  /**
   * <code>PAYLATER_NEWTON = 4;</code>
   */
  public static final int PAYLATER_NEWTON_VALUE = 4;
  /**
   * <code>PAYLATER_BUYNOW = 5;</code>
   */
  public static final int PAYLATER_BUYNOW_VALUE = 5;
  /**
   * <code>CASH_LOAN_FMOB_AMBER = 6;</code>
   */
  public static final int CASH_LOAN_FMOB_AMBER_VALUE = 6;
  /**
   * <code>CASHLOAN_FMFB_AMBER = 7;</code>
   */
  public static final int CASHLOAN_FMFB_AMBER_VALUE = 7;
  /**
   * <code>ALL_PRODUCT = 8;</code>
   */
  public static final int ALL_PRODUCT_VALUE = 8;
  /**
   * <code>LENDING_MARKETPLACE = 9;</code>
   */
  public static final int LENDING_MARKETPLACE_VALUE = 9;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static LoanProductCode valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static LoanProductCode forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN_PRODUCT_CODE;
      case 1: return FINANCE_LENDING_EVNFC;
      case 2: return PAYLATER_LENDING;
      case 3: return PAYLATER_CREDIT_CARD;
      case 4: return PAYLATER_NEWTON;
      case 5: return PAYLATER_BUYNOW;
      case 6: return CASH_LOAN_FMOB_AMBER;
      case 7: return CASHLOAN_FMFB_AMBER;
      case 8: return ALL_PRODUCT;
      case 9: return LENDING_MARKETPLACE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<LoanProductCode>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      LoanProductCode> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<LoanProductCode>() {
          public LoanProductCode findValueByNumber(int number) {
            return LoanProductCode.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.mservice.fs.onboarding.model.notipackage.protomodel.GetOfferPackage.getDescriptor().getEnumTypes().get(0);
  }

  private static final LoanProductCode[] VALUES = values();

  public static LoanProductCode valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private LoanProductCode(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:LoanProductCode)
}

