// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: get_offer_package.proto

package com.mservice.fs.onboarding.model.notipackage.protomodel;

/**
 * Protobuf enum {@code MerchantType}
 */
public enum MerchantType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * default unknown merchant type
   * </pre>
   *
   * <code>UNKNOWN_MERCHANT_TYPE = 0;</code>
   */
  UNKNOWN_MERCHANT_TYPE(0),
  /**
   * <pre>
   * online business (fmob)
   * </pre>
   *
   * <code>MERCHANT_TYPE_ONLINE_BUSINESS = 1;</code>
   */
  MERCHANT_TYPE_ONLINE_BUSINESS(1),
  /**
   * <pre>
   * offline business (fmfb)
   * </pre>
   *
   * <code>MERCHANT_TYPE_OFFLINE_BUSINESS = 2;</code>
   */
  MERCHANT_TYPE_OFFLINE_BUSINESS(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * default unknown merchant type
   * </pre>
   *
   * <code>UNKNOWN_MERCHANT_TYPE = 0;</code>
   */
  public static final int UNKNOWN_MERCHANT_TYPE_VALUE = 0;
  /**
   * <pre>
   * online business (fmob)
   * </pre>
   *
   * <code>MERCHANT_TYPE_ONLINE_BUSINESS = 1;</code>
   */
  public static final int MERCHANT_TYPE_ONLINE_BUSINESS_VALUE = 1;
  /**
   * <pre>
   * offline business (fmfb)
   * </pre>
   *
   * <code>MERCHANT_TYPE_OFFLINE_BUSINESS = 2;</code>
   */
  public static final int MERCHANT_TYPE_OFFLINE_BUSINESS_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MerchantType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static MerchantType forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN_MERCHANT_TYPE;
      case 1: return MERCHANT_TYPE_ONLINE_BUSINESS;
      case 2: return MERCHANT_TYPE_OFFLINE_BUSINESS;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MerchantType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MerchantType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MerchantType>() {
          public MerchantType findValueByNumber(int number) {
            return MerchantType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.mservice.fs.onboarding.model.notipackage.protomodel.GetOfferPackage.getDescriptor().getEnumTypes().get(2);
  }

  private static final MerchantType[] VALUES = values();

  public static MerchantType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MerchantType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:MerchantType)
}

