// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: get_offer_package.proto

package com.mservice.fs.onboarding.model.notipackage.protomodel;

/**
 * Protobuf enum {@code OfferPackageType}
 */
public enum OfferPackageType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOWN_OFFER_PACKAGE_TYPE = 0;</code>
   */
  UNKNOWN_OFFER_PACKAGE_TYPE(0),
  /**
   * <code>PREAPPROVAL_OFFER = 1;</code>
   */
  PREAPPROVAL_OFFER(1),
  /**
   * <code>NORMAL_OFFER = 2;</code>
   */
  NORMAL_OFFER(2),
  /**
   * <code>SPECIAL_OFFER = 3;</code>
   */
  SPECIAL_OFFER(3),
  /**
   * <code>OB30 = 4;</code>
   */
  OB30(4),
  /**
   * <code>OB30_PLUS = 5;</code>
   */
  OB30_PLUS(5),
  /**
   * <code>OB100 = 6;</code>
   */
  OB100(6),
  /**
   * <code>GEN_Z = 7;</code>
   */
  GEN_Z(7),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNKNOWN_OFFER_PACKAGE_TYPE = 0;</code>
   */
  public static final int UNKNOWN_OFFER_PACKAGE_TYPE_VALUE = 0;
  /**
   * <code>PREAPPROVAL_OFFER = 1;</code>
   */
  public static final int PREAPPROVAL_OFFER_VALUE = 1;
  /**
   * <code>NORMAL_OFFER = 2;</code>
   */
  public static final int NORMAL_OFFER_VALUE = 2;
  /**
   * <code>SPECIAL_OFFER = 3;</code>
   */
  public static final int SPECIAL_OFFER_VALUE = 3;
  /**
   * <code>OB30 = 4;</code>
   */
  public static final int OB30_VALUE = 4;
  /**
   * <code>OB30_PLUS = 5;</code>
   */
  public static final int OB30_PLUS_VALUE = 5;
  /**
   * <code>OB100 = 6;</code>
   */
  public static final int OB100_VALUE = 6;
  /**
   * <code>GEN_Z = 7;</code>
   */
  public static final int GEN_Z_VALUE = 7;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static OfferPackageType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static OfferPackageType forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN_OFFER_PACKAGE_TYPE;
      case 1: return PREAPPROVAL_OFFER;
      case 2: return NORMAL_OFFER;
      case 3: return SPECIAL_OFFER;
      case 4: return OB30;
      case 5: return OB30_PLUS;
      case 6: return OB100;
      case 7: return GEN_Z;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<OfferPackageType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      OfferPackageType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<OfferPackageType>() {
          public OfferPackageType findValueByNumber(int number) {
            return OfferPackageType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.mservice.fs.onboarding.model.notipackage.protomodel.GetOfferPackage.getDescriptor().getEnumTypes().get(3);
  }

  private static final OfferPackageType[] VALUES = values();

  public static OfferPackageType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private OfferPackageType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:OfferPackageType)
}

