// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: get_offer_package.proto

package com.mservice.fs.onboarding.model.notipackage.protomodel;

/**
 * Protobuf type {@code OfferPackage}
 */
public final class OfferPackage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:OfferPackage)
    OfferPackageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OfferPackage.newBuilder() to construct.
  private OfferPackage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OfferPackage() {
    packageGroup_ = "";
    packageName_ = "";
    packageCode_ = "";
    lenderId_ = 0;
    packageStatus_ = "";
    packageType_ = "";
    classification_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OfferPackage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OfferPackage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            packageGroup_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            packageName_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            packageCode_ = s;
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            lenderId_ = rawValue;
            break;
          }
          case 40: {

            rank_ = input.readInt32();
            break;
          }
          case 48: {

            packageAmount_ = input.readInt32();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            packageStatus_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            packageType_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            classification_ = s;
            break;
          }
          case 80: {

            tenor_ = input.readInt64();
            break;
          }
          case 89: {

            interestRate_ = input.readDouble();
            break;
          }
          case 101: {

            interestAmount_ = input.readFloat();
            break;
          }
          case 109: {

            disbursedAmount_ = input.readFloat();
            break;
          }
          case 117: {

            paymentAmount_ = input.readFloat();
            break;
          }
          case 125: {

            minLoanAmount_ = input.readFloat();
            break;
          }
          case 133: {

            maxLoanAmount_ = input.readFloat();
            break;
          }
          case 141: {

            serviceFee_ = input.readFloat();
            break;
          }
          case 149: {

            collectionFee_ = input.readFloat();
            break;
          }
          case 157: {

            disbursedFee_ = input.readFloat();
            break;
          }
          case 161: {

            lateInterestRate_ = input.readDouble();
            break;
          }
          case 173: {

            lateFee_ = input.readFloat();
            break;
          }
          case 181: {

            emi_ = input.readFloat();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.mservice.fs.onboarding.model.notipackage.protomodel.GetOfferPackage.internal_static_OfferPackage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mservice.fs.onboarding.model.notipackage.protomodel.GetOfferPackage.internal_static_OfferPackage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage.class, com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage.Builder.class);
  }

  public static final int PACKAGE_GROUP_FIELD_NUMBER = 1;
  private volatile java.lang.Object packageGroup_;
  /**
   * <pre>
   * name of the package group
   * </pre>
   *
   * <code>string package_group = 1;</code>
   * @return The packageGroup.
   */
  @java.lang.Override
  public java.lang.String getPackageGroup() {
    java.lang.Object ref = packageGroup_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      packageGroup_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * name of the package group
   * </pre>
   *
   * <code>string package_group = 1;</code>
   * @return The bytes for packageGroup.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPackageGroupBytes() {
    java.lang.Object ref = packageGroup_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      packageGroup_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PACKAGE_NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object packageName_;
  /**
   * <pre>
   * name of the loan package
   * </pre>
   *
   * <code>string package_name = 2;</code>
   * @return The packageName.
   */
  @java.lang.Override
  public java.lang.String getPackageName() {
    java.lang.Object ref = packageName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      packageName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * name of the loan package
   * </pre>
   *
   * <code>string package_name = 2;</code>
   * @return The bytes for packageName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPackageNameBytes() {
    java.lang.Object ref = packageName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      packageName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PACKAGE_CODE_FIELD_NUMBER = 3;
  private volatile java.lang.Object packageCode_;
  /**
   * <pre>
   * an id of the loan package
   * </pre>
   *
   * <code>string package_code = 3;</code>
   * @return The packageCode.
   */
  @java.lang.Override
  public java.lang.String getPackageCode() {
    java.lang.Object ref = packageCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      packageCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * an id of the loan package
   * </pre>
   *
   * <code>string package_code = 3;</code>
   * @return The bytes for packageCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPackageCodeBytes() {
    java.lang.Object ref = packageCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      packageCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LENDER_ID_FIELD_NUMBER = 4;
  private int lenderId_;
  /**
   * <pre>
   * lender
   * </pre>
   *
   * <code>.Lender lender_id = 4;</code>
   * @return The enum numeric value on the wire for lenderId.
   */
  @java.lang.Override public int getLenderIdValue() {
    return lenderId_;
  }
  /**
   * <pre>
   * lender
   * </pre>
   *
   * <code>.Lender lender_id = 4;</code>
   * @return The lenderId.
   */
  @java.lang.Override public com.mservice.fs.onboarding.model.notipackage.protomodel.Lender getLenderId() {
    @SuppressWarnings("deprecation")
    com.mservice.fs.onboarding.model.notipackage.protomodel.Lender result = com.mservice.fs.onboarding.model.notipackage.protomodel.Lender.valueOf(lenderId_);
    return result == null ? com.mservice.fs.onboarding.model.notipackage.protomodel.Lender.UNRECOGNIZED : result;
  }

  public static final int RANK_FIELD_NUMBER = 5;
  private int rank_;
  /**
   * <pre>
   * rank
   * </pre>
   *
   * <code>int32 rank = 5;</code>
   * @return The rank.
   */
  @java.lang.Override
  public int getRank() {
    return rank_;
  }

  public static final int PACKAGE_AMOUNT_FIELD_NUMBER = 6;
  private int packageAmount_;
  /**
   * <pre>
   * amount of the loan package
   * </pre>
   *
   * <code>int32 package_amount = 6;</code>
   * @return The packageAmount.
   */
  @java.lang.Override
  public int getPackageAmount() {
    return packageAmount_;
  }

  public static final int PACKAGE_STATUS_FIELD_NUMBER = 7;
  private volatile java.lang.Object packageStatus_;
  /**
   * <pre>
   * Package status
   * </pre>
   *
   * <code>string package_status = 7;</code>
   * @return The packageStatus.
   */
  @java.lang.Override
  public java.lang.String getPackageStatus() {
    java.lang.Object ref = packageStatus_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      packageStatus_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Package status
   * </pre>
   *
   * <code>string package_status = 7;</code>
   * @return The bytes for packageStatus.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPackageStatusBytes() {
    java.lang.Object ref = packageStatus_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      packageStatus_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PACKAGE_TYPE_FIELD_NUMBER = 8;
  private volatile java.lang.Object packageType_;
  /**
   * <pre>
   * Package type
   * </pre>
   *
   * <code>string package_type = 8;</code>
   * @return The packageType.
   */
  @java.lang.Override
  public java.lang.String getPackageType() {
    java.lang.Object ref = packageType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      packageType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Package type
   * </pre>
   *
   * <code>string package_type = 8;</code>
   * @return The bytes for packageType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPackageTypeBytes() {
    java.lang.Object ref = packageType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      packageType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLASSIFICATION_FIELD_NUMBER = 9;
  private volatile java.lang.Object classification_;
  /**
   * <pre>
   * Package classification (ex: ALL, OLD_UP_TO_50M, KYB_UP_TO_70M)
   * </pre>
   *
   * <code>string classification = 9;</code>
   * @return The classification.
   */
  @java.lang.Override
  public java.lang.String getClassification() {
    java.lang.Object ref = classification_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      classification_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Package classification (ex: ALL, OLD_UP_TO_50M, KYB_UP_TO_70M)
   * </pre>
   *
   * <code>string classification = 9;</code>
   * @return The bytes for classification.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClassificationBytes() {
    java.lang.Object ref = classification_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      classification_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TENOR_FIELD_NUMBER = 10;
  private long tenor_;
  /**
   * <pre>
   * valid duration for a loan package
   * </pre>
   *
   * <code>int64 tenor = 10;</code>
   * @return The tenor.
   */
  @java.lang.Override
  public long getTenor() {
    return tenor_;
  }

  public static final int INTEREST_RATE_FIELD_NUMBER = 11;
  private double interestRate_;
  /**
   * <pre>
   * the interest rate for on-time payment
   * </pre>
   *
   * <code>double interest_rate = 11;</code>
   * @return The interestRate.
   */
  @java.lang.Override
  public double getInterestRate() {
    return interestRate_;
  }

  public static final int INTEREST_AMOUNT_FIELD_NUMBER = 12;
  private float interestAmount_;
  /**
   * <pre>
   * interest amount
   * </pre>
   *
   * <code>float interest_amount = 12;</code>
   * @return The interestAmount.
   */
  @java.lang.Override
  public float getInterestAmount() {
    return interestAmount_;
  }

  public static final int DISBURSED_AMOUNT_FIELD_NUMBER = 13;
  private float disbursedAmount_;
  /**
   * <pre>
   * amount VND disbursed for users after subtracting all pre-collected fees
   * </pre>
   *
   * <code>float disbursed_amount = 13;</code>
   * @return The disbursedAmount.
   */
  @java.lang.Override
  public float getDisbursedAmount() {
    return disbursedAmount_;
  }

  public static final int PAYMENT_AMOUNT_FIELD_NUMBER = 14;
  private float paymentAmount_;
  /**
   * <pre>
   * fixed payment amount VND needed to pay for each period
   * </pre>
   *
   * <code>float payment_amount = 14;</code>
   * @return The paymentAmount.
   */
  @java.lang.Override
  public float getPaymentAmount() {
    return paymentAmount_;
  }

  public static final int MIN_LOAN_AMOUNT_FIELD_NUMBER = 15;
  private float minLoanAmount_;
  /**
   * <pre>
   * minimum loan amount
   * </pre>
   *
   * <code>float min_loan_amount = 15;</code>
   * @return The minLoanAmount.
   */
  @java.lang.Override
  public float getMinLoanAmount() {
    return minLoanAmount_;
  }

  public static final int MAX_LOAN_AMOUNT_FIELD_NUMBER = 16;
  private float maxLoanAmount_;
  /**
   * <pre>
   * maximum loan amount
   * </pre>
   *
   * <code>float max_loan_amount = 16;</code>
   * @return The maxLoanAmount.
   */
  @java.lang.Override
  public float getMaxLoanAmount() {
    return maxLoanAmount_;
  }

  public static final int SERVICE_FEE_FIELD_NUMBER = 17;
  private float serviceFee_;
  /**
   * <pre>
   * the fee for using the service
   * </pre>
   *
   * <code>float service_fee = 17;</code>
   * @return The serviceFee.
   */
  @java.lang.Override
  public float getServiceFee() {
    return serviceFee_;
  }

  public static final int COLLECTION_FEE_FIELD_NUMBER = 18;
  private float collectionFee_;
  /**
   * <pre>
   * the collection cost for collecting debt
   * </pre>
   *
   * <code>float collection_fee = 18;</code>
   * @return The collectionFee.
   */
  @java.lang.Override
  public float getCollectionFee() {
    return collectionFee_;
  }

  public static final int DISBURSED_FEE_FIELD_NUMBER = 19;
  private float disbursedFee_;
  /**
   * <pre>
   * the fee of amount disbursed
   * </pre>
   *
   * <code>float disbursed_fee = 19;</code>
   * @return The disbursedFee.
   */
  @java.lang.Override
  public float getDisbursedFee() {
    return disbursedFee_;
  }

  public static final int LATE_INTEREST_RATE_FIELD_NUMBER = 20;
  private double lateInterestRate_;
  /**
   * <pre>
   * interest rate for late payment
   * </pre>
   *
   * <code>double late_interest_rate = 20;</code>
   * @return The lateInterestRate.
   */
  @java.lang.Override
  public double getLateInterestRate() {
    return lateInterestRate_;
  }

  public static final int LATE_FEE_FIELD_NUMBER = 21;
  private float lateFee_;
  /**
   * <pre>
   * penalty late fee
   * </pre>
   *
   * <code>float late_fee = 21;</code>
   * @return The lateFee.
   */
  @java.lang.Override
  public float getLateFee() {
    return lateFee_;
  }

  public static final int EMI_FIELD_NUMBER = 22;
  private float emi_;
  /**
   * <pre>
   * Equated Monthly Installment
   * </pre>
   *
   * <code>float emi = 22;</code>
   * @return The emi.
   */
  @java.lang.Override
  public float getEmi() {
    return emi_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getPackageGroupBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, packageGroup_);
    }
    if (!getPackageNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, packageName_);
    }
    if (!getPackageCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, packageCode_);
    }
    if (lenderId_ != com.mservice.fs.onboarding.model.notipackage.protomodel.Lender.UNKNOWN_LENDER.getNumber()) {
      output.writeEnum(4, lenderId_);
    }
    if (rank_ != 0) {
      output.writeInt32(5, rank_);
    }
    if (packageAmount_ != 0) {
      output.writeInt32(6, packageAmount_);
    }
    if (!getPackageStatusBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, packageStatus_);
    }
    if (!getPackageTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, packageType_);
    }
    if (!getClassificationBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, classification_);
    }
    if (tenor_ != 0L) {
      output.writeInt64(10, tenor_);
    }
    if (interestRate_ != 0D) {
      output.writeDouble(11, interestRate_);
    }
    if (interestAmount_ != 0F) {
      output.writeFloat(12, interestAmount_);
    }
    if (disbursedAmount_ != 0F) {
      output.writeFloat(13, disbursedAmount_);
    }
    if (paymentAmount_ != 0F) {
      output.writeFloat(14, paymentAmount_);
    }
    if (minLoanAmount_ != 0F) {
      output.writeFloat(15, minLoanAmount_);
    }
    if (maxLoanAmount_ != 0F) {
      output.writeFloat(16, maxLoanAmount_);
    }
    if (serviceFee_ != 0F) {
      output.writeFloat(17, serviceFee_);
    }
    if (collectionFee_ != 0F) {
      output.writeFloat(18, collectionFee_);
    }
    if (disbursedFee_ != 0F) {
      output.writeFloat(19, disbursedFee_);
    }
    if (lateInterestRate_ != 0D) {
      output.writeDouble(20, lateInterestRate_);
    }
    if (lateFee_ != 0F) {
      output.writeFloat(21, lateFee_);
    }
    if (emi_ != 0F) {
      output.writeFloat(22, emi_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getPackageGroupBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, packageGroup_);
    }
    if (!getPackageNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, packageName_);
    }
    if (!getPackageCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, packageCode_);
    }
    if (lenderId_ != com.mservice.fs.onboarding.model.notipackage.protomodel.Lender.UNKNOWN_LENDER.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, lenderId_);
    }
    if (rank_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, rank_);
    }
    if (packageAmount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, packageAmount_);
    }
    if (!getPackageStatusBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, packageStatus_);
    }
    if (!getPackageTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, packageType_);
    }
    if (!getClassificationBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, classification_);
    }
    if (tenor_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(10, tenor_);
    }
    if (interestRate_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(11, interestRate_);
    }
    if (interestAmount_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(12, interestAmount_);
    }
    if (disbursedAmount_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(13, disbursedAmount_);
    }
    if (paymentAmount_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(14, paymentAmount_);
    }
    if (minLoanAmount_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(15, minLoanAmount_);
    }
    if (maxLoanAmount_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(16, maxLoanAmount_);
    }
    if (serviceFee_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(17, serviceFee_);
    }
    if (collectionFee_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(18, collectionFee_);
    }
    if (disbursedFee_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(19, disbursedFee_);
    }
    if (lateInterestRate_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(20, lateInterestRate_);
    }
    if (lateFee_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(21, lateFee_);
    }
    if (emi_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(22, emi_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage)) {
      return super.equals(obj);
    }
    com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage other = (com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage) obj;

    if (!getPackageGroup()
        .equals(other.getPackageGroup())) return false;
    if (!getPackageName()
        .equals(other.getPackageName())) return false;
    if (!getPackageCode()
        .equals(other.getPackageCode())) return false;
    if (lenderId_ != other.lenderId_) return false;
    if (getRank()
        != other.getRank()) return false;
    if (getPackageAmount()
        != other.getPackageAmount()) return false;
    if (!getPackageStatus()
        .equals(other.getPackageStatus())) return false;
    if (!getPackageType()
        .equals(other.getPackageType())) return false;
    if (!getClassification()
        .equals(other.getClassification())) return false;
    if (getTenor()
        != other.getTenor()) return false;
    if (java.lang.Double.doubleToLongBits(getInterestRate())
        != java.lang.Double.doubleToLongBits(
            other.getInterestRate())) return false;
    if (java.lang.Float.floatToIntBits(getInterestAmount())
        != java.lang.Float.floatToIntBits(
            other.getInterestAmount())) return false;
    if (java.lang.Float.floatToIntBits(getDisbursedAmount())
        != java.lang.Float.floatToIntBits(
            other.getDisbursedAmount())) return false;
    if (java.lang.Float.floatToIntBits(getPaymentAmount())
        != java.lang.Float.floatToIntBits(
            other.getPaymentAmount())) return false;
    if (java.lang.Float.floatToIntBits(getMinLoanAmount())
        != java.lang.Float.floatToIntBits(
            other.getMinLoanAmount())) return false;
    if (java.lang.Float.floatToIntBits(getMaxLoanAmount())
        != java.lang.Float.floatToIntBits(
            other.getMaxLoanAmount())) return false;
    if (java.lang.Float.floatToIntBits(getServiceFee())
        != java.lang.Float.floatToIntBits(
            other.getServiceFee())) return false;
    if (java.lang.Float.floatToIntBits(getCollectionFee())
        != java.lang.Float.floatToIntBits(
            other.getCollectionFee())) return false;
    if (java.lang.Float.floatToIntBits(getDisbursedFee())
        != java.lang.Float.floatToIntBits(
            other.getDisbursedFee())) return false;
    if (java.lang.Double.doubleToLongBits(getLateInterestRate())
        != java.lang.Double.doubleToLongBits(
            other.getLateInterestRate())) return false;
    if (java.lang.Float.floatToIntBits(getLateFee())
        != java.lang.Float.floatToIntBits(
            other.getLateFee())) return false;
    if (java.lang.Float.floatToIntBits(getEmi())
        != java.lang.Float.floatToIntBits(
            other.getEmi())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PACKAGE_GROUP_FIELD_NUMBER;
    hash = (53 * hash) + getPackageGroup().hashCode();
    hash = (37 * hash) + PACKAGE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getPackageName().hashCode();
    hash = (37 * hash) + PACKAGE_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getPackageCode().hashCode();
    hash = (37 * hash) + LENDER_ID_FIELD_NUMBER;
    hash = (53 * hash) + lenderId_;
    hash = (37 * hash) + RANK_FIELD_NUMBER;
    hash = (53 * hash) + getRank();
    hash = (37 * hash) + PACKAGE_AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getPackageAmount();
    hash = (37 * hash) + PACKAGE_STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getPackageStatus().hashCode();
    hash = (37 * hash) + PACKAGE_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getPackageType().hashCode();
    hash = (37 * hash) + CLASSIFICATION_FIELD_NUMBER;
    hash = (53 * hash) + getClassification().hashCode();
    hash = (37 * hash) + TENOR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTenor());
    hash = (37 * hash) + INTEREST_RATE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getInterestRate()));
    hash = (37 * hash) + INTEREST_AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getInterestAmount());
    hash = (37 * hash) + DISBURSED_AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getDisbursedAmount());
    hash = (37 * hash) + PAYMENT_AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getPaymentAmount());
    hash = (37 * hash) + MIN_LOAN_AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getMinLoanAmount());
    hash = (37 * hash) + MAX_LOAN_AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getMaxLoanAmount());
    hash = (37 * hash) + SERVICE_FEE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getServiceFee());
    hash = (37 * hash) + COLLECTION_FEE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getCollectionFee());
    hash = (37 * hash) + DISBURSED_FEE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getDisbursedFee());
    hash = (37 * hash) + LATE_INTEREST_RATE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getLateInterestRate()));
    hash = (37 * hash) + LATE_FEE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getLateFee());
    hash = (37 * hash) + EMI_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getEmi());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code OfferPackage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:OfferPackage)
      com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mservice.fs.onboarding.model.notipackage.protomodel.GetOfferPackage.internal_static_OfferPackage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mservice.fs.onboarding.model.notipackage.protomodel.GetOfferPackage.internal_static_OfferPackage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage.class, com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage.Builder.class);
    }

    // Construct using com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      packageGroup_ = "";

      packageName_ = "";

      packageCode_ = "";

      lenderId_ = 0;

      rank_ = 0;

      packageAmount_ = 0;

      packageStatus_ = "";

      packageType_ = "";

      classification_ = "";

      tenor_ = 0L;

      interestRate_ = 0D;

      interestAmount_ = 0F;

      disbursedAmount_ = 0F;

      paymentAmount_ = 0F;

      minLoanAmount_ = 0F;

      maxLoanAmount_ = 0F;

      serviceFee_ = 0F;

      collectionFee_ = 0F;

      disbursedFee_ = 0F;

      lateInterestRate_ = 0D;

      lateFee_ = 0F;

      emi_ = 0F;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.mservice.fs.onboarding.model.notipackage.protomodel.GetOfferPackage.internal_static_OfferPackage_descriptor;
    }

    @java.lang.Override
    public com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage getDefaultInstanceForType() {
      return com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage.getDefaultInstance();
    }

    @java.lang.Override
    public com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage build() {
      com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage buildPartial() {
      com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage result = new com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage(this);
      result.packageGroup_ = packageGroup_;
      result.packageName_ = packageName_;
      result.packageCode_ = packageCode_;
      result.lenderId_ = lenderId_;
      result.rank_ = rank_;
      result.packageAmount_ = packageAmount_;
      result.packageStatus_ = packageStatus_;
      result.packageType_ = packageType_;
      result.classification_ = classification_;
      result.tenor_ = tenor_;
      result.interestRate_ = interestRate_;
      result.interestAmount_ = interestAmount_;
      result.disbursedAmount_ = disbursedAmount_;
      result.paymentAmount_ = paymentAmount_;
      result.minLoanAmount_ = minLoanAmount_;
      result.maxLoanAmount_ = maxLoanAmount_;
      result.serviceFee_ = serviceFee_;
      result.collectionFee_ = collectionFee_;
      result.disbursedFee_ = disbursedFee_;
      result.lateInterestRate_ = lateInterestRate_;
      result.lateFee_ = lateFee_;
      result.emi_ = emi_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage) {
        return mergeFrom((com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage other) {
      if (other == com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage.getDefaultInstance()) return this;
      if (!other.getPackageGroup().isEmpty()) {
        packageGroup_ = other.packageGroup_;
        onChanged();
      }
      if (!other.getPackageName().isEmpty()) {
        packageName_ = other.packageName_;
        onChanged();
      }
      if (!other.getPackageCode().isEmpty()) {
        packageCode_ = other.packageCode_;
        onChanged();
      }
      if (other.lenderId_ != 0) {
        setLenderIdValue(other.getLenderIdValue());
      }
      if (other.getRank() != 0) {
        setRank(other.getRank());
      }
      if (other.getPackageAmount() != 0) {
        setPackageAmount(other.getPackageAmount());
      }
      if (!other.getPackageStatus().isEmpty()) {
        packageStatus_ = other.packageStatus_;
        onChanged();
      }
      if (!other.getPackageType().isEmpty()) {
        packageType_ = other.packageType_;
        onChanged();
      }
      if (!other.getClassification().isEmpty()) {
        classification_ = other.classification_;
        onChanged();
      }
      if (other.getTenor() != 0L) {
        setTenor(other.getTenor());
      }
      if (other.getInterestRate() != 0D) {
        setInterestRate(other.getInterestRate());
      }
      if (other.getInterestAmount() != 0F) {
        setInterestAmount(other.getInterestAmount());
      }
      if (other.getDisbursedAmount() != 0F) {
        setDisbursedAmount(other.getDisbursedAmount());
      }
      if (other.getPaymentAmount() != 0F) {
        setPaymentAmount(other.getPaymentAmount());
      }
      if (other.getMinLoanAmount() != 0F) {
        setMinLoanAmount(other.getMinLoanAmount());
      }
      if (other.getMaxLoanAmount() != 0F) {
        setMaxLoanAmount(other.getMaxLoanAmount());
      }
      if (other.getServiceFee() != 0F) {
        setServiceFee(other.getServiceFee());
      }
      if (other.getCollectionFee() != 0F) {
        setCollectionFee(other.getCollectionFee());
      }
      if (other.getDisbursedFee() != 0F) {
        setDisbursedFee(other.getDisbursedFee());
      }
      if (other.getLateInterestRate() != 0D) {
        setLateInterestRate(other.getLateInterestRate());
      }
      if (other.getLateFee() != 0F) {
        setLateFee(other.getLateFee());
      }
      if (other.getEmi() != 0F) {
        setEmi(other.getEmi());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object packageGroup_ = "";
    /**
     * <pre>
     * name of the package group
     * </pre>
     *
     * <code>string package_group = 1;</code>
     * @return The packageGroup.
     */
    public java.lang.String getPackageGroup() {
      java.lang.Object ref = packageGroup_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        packageGroup_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * name of the package group
     * </pre>
     *
     * <code>string package_group = 1;</code>
     * @return The bytes for packageGroup.
     */
    public com.google.protobuf.ByteString
        getPackageGroupBytes() {
      java.lang.Object ref = packageGroup_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        packageGroup_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * name of the package group
     * </pre>
     *
     * <code>string package_group = 1;</code>
     * @param value The packageGroup to set.
     * @return This builder for chaining.
     */
    public Builder setPackageGroup(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      packageGroup_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * name of the package group
     * </pre>
     *
     * <code>string package_group = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPackageGroup() {
      
      packageGroup_ = getDefaultInstance().getPackageGroup();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * name of the package group
     * </pre>
     *
     * <code>string package_group = 1;</code>
     * @param value The bytes for packageGroup to set.
     * @return This builder for chaining.
     */
    public Builder setPackageGroupBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      packageGroup_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object packageName_ = "";
    /**
     * <pre>
     * name of the loan package
     * </pre>
     *
     * <code>string package_name = 2;</code>
     * @return The packageName.
     */
    public java.lang.String getPackageName() {
      java.lang.Object ref = packageName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        packageName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * name of the loan package
     * </pre>
     *
     * <code>string package_name = 2;</code>
     * @return The bytes for packageName.
     */
    public com.google.protobuf.ByteString
        getPackageNameBytes() {
      java.lang.Object ref = packageName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        packageName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * name of the loan package
     * </pre>
     *
     * <code>string package_name = 2;</code>
     * @param value The packageName to set.
     * @return This builder for chaining.
     */
    public Builder setPackageName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      packageName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * name of the loan package
     * </pre>
     *
     * <code>string package_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPackageName() {
      
      packageName_ = getDefaultInstance().getPackageName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * name of the loan package
     * </pre>
     *
     * <code>string package_name = 2;</code>
     * @param value The bytes for packageName to set.
     * @return This builder for chaining.
     */
    public Builder setPackageNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      packageName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object packageCode_ = "";
    /**
     * <pre>
     * an id of the loan package
     * </pre>
     *
     * <code>string package_code = 3;</code>
     * @return The packageCode.
     */
    public java.lang.String getPackageCode() {
      java.lang.Object ref = packageCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        packageCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * an id of the loan package
     * </pre>
     *
     * <code>string package_code = 3;</code>
     * @return The bytes for packageCode.
     */
    public com.google.protobuf.ByteString
        getPackageCodeBytes() {
      java.lang.Object ref = packageCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        packageCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * an id of the loan package
     * </pre>
     *
     * <code>string package_code = 3;</code>
     * @param value The packageCode to set.
     * @return This builder for chaining.
     */
    public Builder setPackageCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      packageCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * an id of the loan package
     * </pre>
     *
     * <code>string package_code = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPackageCode() {
      
      packageCode_ = getDefaultInstance().getPackageCode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * an id of the loan package
     * </pre>
     *
     * <code>string package_code = 3;</code>
     * @param value The bytes for packageCode to set.
     * @return This builder for chaining.
     */
    public Builder setPackageCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      packageCode_ = value;
      onChanged();
      return this;
    }

    private int lenderId_ = 0;
    /**
     * <pre>
     * lender
     * </pre>
     *
     * <code>.Lender lender_id = 4;</code>
     * @return The enum numeric value on the wire for lenderId.
     */
    @java.lang.Override public int getLenderIdValue() {
      return lenderId_;
    }
    /**
     * <pre>
     * lender
     * </pre>
     *
     * <code>.Lender lender_id = 4;</code>
     * @param value The enum numeric value on the wire for lenderId to set.
     * @return This builder for chaining.
     */
    public Builder setLenderIdValue(int value) {
      
      lenderId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * lender
     * </pre>
     *
     * <code>.Lender lender_id = 4;</code>
     * @return The lenderId.
     */
    @java.lang.Override
    public com.mservice.fs.onboarding.model.notipackage.protomodel.Lender getLenderId() {
      @SuppressWarnings("deprecation")
      com.mservice.fs.onboarding.model.notipackage.protomodel.Lender result = com.mservice.fs.onboarding.model.notipackage.protomodel.Lender.valueOf(lenderId_);
      return result == null ? com.mservice.fs.onboarding.model.notipackage.protomodel.Lender.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * lender
     * </pre>
     *
     * <code>.Lender lender_id = 4;</code>
     * @param value The lenderId to set.
     * @return This builder for chaining.
     */
    public Builder setLenderId(com.mservice.fs.onboarding.model.notipackage.protomodel.Lender value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      lenderId_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * lender
     * </pre>
     *
     * <code>.Lender lender_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLenderId() {
      
      lenderId_ = 0;
      onChanged();
      return this;
    }

    private int rank_ ;
    /**
     * <pre>
     * rank
     * </pre>
     *
     * <code>int32 rank = 5;</code>
     * @return The rank.
     */
    @java.lang.Override
    public int getRank() {
      return rank_;
    }
    /**
     * <pre>
     * rank
     * </pre>
     *
     * <code>int32 rank = 5;</code>
     * @param value The rank to set.
     * @return This builder for chaining.
     */
    public Builder setRank(int value) {
      
      rank_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * rank
     * </pre>
     *
     * <code>int32 rank = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearRank() {
      
      rank_ = 0;
      onChanged();
      return this;
    }

    private int packageAmount_ ;
    /**
     * <pre>
     * amount of the loan package
     * </pre>
     *
     * <code>int32 package_amount = 6;</code>
     * @return The packageAmount.
     */
    @java.lang.Override
    public int getPackageAmount() {
      return packageAmount_;
    }
    /**
     * <pre>
     * amount of the loan package
     * </pre>
     *
     * <code>int32 package_amount = 6;</code>
     * @param value The packageAmount to set.
     * @return This builder for chaining.
     */
    public Builder setPackageAmount(int value) {
      
      packageAmount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * amount of the loan package
     * </pre>
     *
     * <code>int32 package_amount = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPackageAmount() {
      
      packageAmount_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object packageStatus_ = "";
    /**
     * <pre>
     * Package status
     * </pre>
     *
     * <code>string package_status = 7;</code>
     * @return The packageStatus.
     */
    public java.lang.String getPackageStatus() {
      java.lang.Object ref = packageStatus_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        packageStatus_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Package status
     * </pre>
     *
     * <code>string package_status = 7;</code>
     * @return The bytes for packageStatus.
     */
    public com.google.protobuf.ByteString
        getPackageStatusBytes() {
      java.lang.Object ref = packageStatus_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        packageStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Package status
     * </pre>
     *
     * <code>string package_status = 7;</code>
     * @param value The packageStatus to set.
     * @return This builder for chaining.
     */
    public Builder setPackageStatus(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      packageStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Package status
     * </pre>
     *
     * <code>string package_status = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearPackageStatus() {
      
      packageStatus_ = getDefaultInstance().getPackageStatus();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Package status
     * </pre>
     *
     * <code>string package_status = 7;</code>
     * @param value The bytes for packageStatus to set.
     * @return This builder for chaining.
     */
    public Builder setPackageStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      packageStatus_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object packageType_ = "";
    /**
     * <pre>
     * Package type
     * </pre>
     *
     * <code>string package_type = 8;</code>
     * @return The packageType.
     */
    public java.lang.String getPackageType() {
      java.lang.Object ref = packageType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        packageType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Package type
     * </pre>
     *
     * <code>string package_type = 8;</code>
     * @return The bytes for packageType.
     */
    public com.google.protobuf.ByteString
        getPackageTypeBytes() {
      java.lang.Object ref = packageType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        packageType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Package type
     * </pre>
     *
     * <code>string package_type = 8;</code>
     * @param value The packageType to set.
     * @return This builder for chaining.
     */
    public Builder setPackageType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      packageType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Package type
     * </pre>
     *
     * <code>string package_type = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearPackageType() {
      
      packageType_ = getDefaultInstance().getPackageType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Package type
     * </pre>
     *
     * <code>string package_type = 8;</code>
     * @param value The bytes for packageType to set.
     * @return This builder for chaining.
     */
    public Builder setPackageTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      packageType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object classification_ = "";
    /**
     * <pre>
     * Package classification (ex: ALL, OLD_UP_TO_50M, KYB_UP_TO_70M)
     * </pre>
     *
     * <code>string classification = 9;</code>
     * @return The classification.
     */
    public java.lang.String getClassification() {
      java.lang.Object ref = classification_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        classification_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Package classification (ex: ALL, OLD_UP_TO_50M, KYB_UP_TO_70M)
     * </pre>
     *
     * <code>string classification = 9;</code>
     * @return The bytes for classification.
     */
    public com.google.protobuf.ByteString
        getClassificationBytes() {
      java.lang.Object ref = classification_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        classification_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Package classification (ex: ALL, OLD_UP_TO_50M, KYB_UP_TO_70M)
     * </pre>
     *
     * <code>string classification = 9;</code>
     * @param value The classification to set.
     * @return This builder for chaining.
     */
    public Builder setClassification(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      classification_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Package classification (ex: ALL, OLD_UP_TO_50M, KYB_UP_TO_70M)
     * </pre>
     *
     * <code>string classification = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearClassification() {
      
      classification_ = getDefaultInstance().getClassification();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Package classification (ex: ALL, OLD_UP_TO_50M, KYB_UP_TO_70M)
     * </pre>
     *
     * <code>string classification = 9;</code>
     * @param value The bytes for classification to set.
     * @return This builder for chaining.
     */
    public Builder setClassificationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      classification_ = value;
      onChanged();
      return this;
    }

    private long tenor_ ;
    /**
     * <pre>
     * valid duration for a loan package
     * </pre>
     *
     * <code>int64 tenor = 10;</code>
     * @return The tenor.
     */
    @java.lang.Override
    public long getTenor() {
      return tenor_;
    }
    /**
     * <pre>
     * valid duration for a loan package
     * </pre>
     *
     * <code>int64 tenor = 10;</code>
     * @param value The tenor to set.
     * @return This builder for chaining.
     */
    public Builder setTenor(long value) {
      
      tenor_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * valid duration for a loan package
     * </pre>
     *
     * <code>int64 tenor = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearTenor() {
      
      tenor_ = 0L;
      onChanged();
      return this;
    }

    private double interestRate_ ;
    /**
     * <pre>
     * the interest rate for on-time payment
     * </pre>
     *
     * <code>double interest_rate = 11;</code>
     * @return The interestRate.
     */
    @java.lang.Override
    public double getInterestRate() {
      return interestRate_;
    }
    /**
     * <pre>
     * the interest rate for on-time payment
     * </pre>
     *
     * <code>double interest_rate = 11;</code>
     * @param value The interestRate to set.
     * @return This builder for chaining.
     */
    public Builder setInterestRate(double value) {
      
      interestRate_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the interest rate for on-time payment
     * </pre>
     *
     * <code>double interest_rate = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearInterestRate() {
      
      interestRate_ = 0D;
      onChanged();
      return this;
    }

    private float interestAmount_ ;
    /**
     * <pre>
     * interest amount
     * </pre>
     *
     * <code>float interest_amount = 12;</code>
     * @return The interestAmount.
     */
    @java.lang.Override
    public float getInterestAmount() {
      return interestAmount_;
    }
    /**
     * <pre>
     * interest amount
     * </pre>
     *
     * <code>float interest_amount = 12;</code>
     * @param value The interestAmount to set.
     * @return This builder for chaining.
     */
    public Builder setInterestAmount(float value) {
      
      interestAmount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * interest amount
     * </pre>
     *
     * <code>float interest_amount = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearInterestAmount() {
      
      interestAmount_ = 0F;
      onChanged();
      return this;
    }

    private float disbursedAmount_ ;
    /**
     * <pre>
     * amount VND disbursed for users after subtracting all pre-collected fees
     * </pre>
     *
     * <code>float disbursed_amount = 13;</code>
     * @return The disbursedAmount.
     */
    @java.lang.Override
    public float getDisbursedAmount() {
      return disbursedAmount_;
    }
    /**
     * <pre>
     * amount VND disbursed for users after subtracting all pre-collected fees
     * </pre>
     *
     * <code>float disbursed_amount = 13;</code>
     * @param value The disbursedAmount to set.
     * @return This builder for chaining.
     */
    public Builder setDisbursedAmount(float value) {
      
      disbursedAmount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * amount VND disbursed for users after subtracting all pre-collected fees
     * </pre>
     *
     * <code>float disbursed_amount = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearDisbursedAmount() {
      
      disbursedAmount_ = 0F;
      onChanged();
      return this;
    }

    private float paymentAmount_ ;
    /**
     * <pre>
     * fixed payment amount VND needed to pay for each period
     * </pre>
     *
     * <code>float payment_amount = 14;</code>
     * @return The paymentAmount.
     */
    @java.lang.Override
    public float getPaymentAmount() {
      return paymentAmount_;
    }
    /**
     * <pre>
     * fixed payment amount VND needed to pay for each period
     * </pre>
     *
     * <code>float payment_amount = 14;</code>
     * @param value The paymentAmount to set.
     * @return This builder for chaining.
     */
    public Builder setPaymentAmount(float value) {
      
      paymentAmount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * fixed payment amount VND needed to pay for each period
     * </pre>
     *
     * <code>float payment_amount = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearPaymentAmount() {
      
      paymentAmount_ = 0F;
      onChanged();
      return this;
    }

    private float minLoanAmount_ ;
    /**
     * <pre>
     * minimum loan amount
     * </pre>
     *
     * <code>float min_loan_amount = 15;</code>
     * @return The minLoanAmount.
     */
    @java.lang.Override
    public float getMinLoanAmount() {
      return minLoanAmount_;
    }
    /**
     * <pre>
     * minimum loan amount
     * </pre>
     *
     * <code>float min_loan_amount = 15;</code>
     * @param value The minLoanAmount to set.
     * @return This builder for chaining.
     */
    public Builder setMinLoanAmount(float value) {
      
      minLoanAmount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * minimum loan amount
     * </pre>
     *
     * <code>float min_loan_amount = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinLoanAmount() {
      
      minLoanAmount_ = 0F;
      onChanged();
      return this;
    }

    private float maxLoanAmount_ ;
    /**
     * <pre>
     * maximum loan amount
     * </pre>
     *
     * <code>float max_loan_amount = 16;</code>
     * @return The maxLoanAmount.
     */
    @java.lang.Override
    public float getMaxLoanAmount() {
      return maxLoanAmount_;
    }
    /**
     * <pre>
     * maximum loan amount
     * </pre>
     *
     * <code>float max_loan_amount = 16;</code>
     * @param value The maxLoanAmount to set.
     * @return This builder for chaining.
     */
    public Builder setMaxLoanAmount(float value) {
      
      maxLoanAmount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * maximum loan amount
     * </pre>
     *
     * <code>float max_loan_amount = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxLoanAmount() {
      
      maxLoanAmount_ = 0F;
      onChanged();
      return this;
    }

    private float serviceFee_ ;
    /**
     * <pre>
     * the fee for using the service
     * </pre>
     *
     * <code>float service_fee = 17;</code>
     * @return The serviceFee.
     */
    @java.lang.Override
    public float getServiceFee() {
      return serviceFee_;
    }
    /**
     * <pre>
     * the fee for using the service
     * </pre>
     *
     * <code>float service_fee = 17;</code>
     * @param value The serviceFee to set.
     * @return This builder for chaining.
     */
    public Builder setServiceFee(float value) {
      
      serviceFee_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the fee for using the service
     * </pre>
     *
     * <code>float service_fee = 17;</code>
     * @return This builder for chaining.
     */
    public Builder clearServiceFee() {
      
      serviceFee_ = 0F;
      onChanged();
      return this;
    }

    private float collectionFee_ ;
    /**
     * <pre>
     * the collection cost for collecting debt
     * </pre>
     *
     * <code>float collection_fee = 18;</code>
     * @return The collectionFee.
     */
    @java.lang.Override
    public float getCollectionFee() {
      return collectionFee_;
    }
    /**
     * <pre>
     * the collection cost for collecting debt
     * </pre>
     *
     * <code>float collection_fee = 18;</code>
     * @param value The collectionFee to set.
     * @return This builder for chaining.
     */
    public Builder setCollectionFee(float value) {
      
      collectionFee_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the collection cost for collecting debt
     * </pre>
     *
     * <code>float collection_fee = 18;</code>
     * @return This builder for chaining.
     */
    public Builder clearCollectionFee() {
      
      collectionFee_ = 0F;
      onChanged();
      return this;
    }

    private float disbursedFee_ ;
    /**
     * <pre>
     * the fee of amount disbursed
     * </pre>
     *
     * <code>float disbursed_fee = 19;</code>
     * @return The disbursedFee.
     */
    @java.lang.Override
    public float getDisbursedFee() {
      return disbursedFee_;
    }
    /**
     * <pre>
     * the fee of amount disbursed
     * </pre>
     *
     * <code>float disbursed_fee = 19;</code>
     * @param value The disbursedFee to set.
     * @return This builder for chaining.
     */
    public Builder setDisbursedFee(float value) {
      
      disbursedFee_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the fee of amount disbursed
     * </pre>
     *
     * <code>float disbursed_fee = 19;</code>
     * @return This builder for chaining.
     */
    public Builder clearDisbursedFee() {
      
      disbursedFee_ = 0F;
      onChanged();
      return this;
    }

    private double lateInterestRate_ ;
    /**
     * <pre>
     * interest rate for late payment
     * </pre>
     *
     * <code>double late_interest_rate = 20;</code>
     * @return The lateInterestRate.
     */
    @java.lang.Override
    public double getLateInterestRate() {
      return lateInterestRate_;
    }
    /**
     * <pre>
     * interest rate for late payment
     * </pre>
     *
     * <code>double late_interest_rate = 20;</code>
     * @param value The lateInterestRate to set.
     * @return This builder for chaining.
     */
    public Builder setLateInterestRate(double value) {
      
      lateInterestRate_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * interest rate for late payment
     * </pre>
     *
     * <code>double late_interest_rate = 20;</code>
     * @return This builder for chaining.
     */
    public Builder clearLateInterestRate() {
      
      lateInterestRate_ = 0D;
      onChanged();
      return this;
    }

    private float lateFee_ ;
    /**
     * <pre>
     * penalty late fee
     * </pre>
     *
     * <code>float late_fee = 21;</code>
     * @return The lateFee.
     */
    @java.lang.Override
    public float getLateFee() {
      return lateFee_;
    }
    /**
     * <pre>
     * penalty late fee
     * </pre>
     *
     * <code>float late_fee = 21;</code>
     * @param value The lateFee to set.
     * @return This builder for chaining.
     */
    public Builder setLateFee(float value) {
      
      lateFee_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * penalty late fee
     * </pre>
     *
     * <code>float late_fee = 21;</code>
     * @return This builder for chaining.
     */
    public Builder clearLateFee() {
      
      lateFee_ = 0F;
      onChanged();
      return this;
    }

    private float emi_ ;
    /**
     * <pre>
     * Equated Monthly Installment
     * </pre>
     *
     * <code>float emi = 22;</code>
     * @return The emi.
     */
    @java.lang.Override
    public float getEmi() {
      return emi_;
    }
    /**
     * <pre>
     * Equated Monthly Installment
     * </pre>
     *
     * <code>float emi = 22;</code>
     * @param value The emi to set.
     * @return This builder for chaining.
     */
    public Builder setEmi(float value) {
      
      emi_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Equated Monthly Installment
     * </pre>
     *
     * <code>float emi = 22;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmi() {
      
      emi_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:OfferPackage)
  }

  // @@protoc_insertion_point(class_scope:OfferPackage)
  private static final com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage();
  }

  public static com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OfferPackage>
      PARSER = new com.google.protobuf.AbstractParser<OfferPackage>() {
    @java.lang.Override
    public OfferPackage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OfferPackage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OfferPackage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OfferPackage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.mservice.fs.onboarding.model.notipackage.protomodel.OfferPackage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

