// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: get_offer_package.proto

package com.mservice.fs.onboarding.model.notipackage.protomodel;

public interface OfferPackageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OfferPackage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * name of the package group
   * </pre>
   *
   * <code>string package_group = 1;</code>
   * @return The packageGroup.
   */
  java.lang.String getPackageGroup();
  /**
   * <pre>
   * name of the package group
   * </pre>
   *
   * <code>string package_group = 1;</code>
   * @return The bytes for packageGroup.
   */
  com.google.protobuf.ByteString
      getPackageGroupBytes();

  /**
   * <pre>
   * name of the loan package
   * </pre>
   *
   * <code>string package_name = 2;</code>
   * @return The packageName.
   */
  java.lang.String getPackageName();
  /**
   * <pre>
   * name of the loan package
   * </pre>
   *
   * <code>string package_name = 2;</code>
   * @return The bytes for packageName.
   */
  com.google.protobuf.ByteString
      getPackageNameBytes();

  /**
   * <pre>
   * an id of the loan package
   * </pre>
   *
   * <code>string package_code = 3;</code>
   * @return The packageCode.
   */
  java.lang.String getPackageCode();
  /**
   * <pre>
   * an id of the loan package
   * </pre>
   *
   * <code>string package_code = 3;</code>
   * @return The bytes for packageCode.
   */
  com.google.protobuf.ByteString
      getPackageCodeBytes();

  /**
   * <pre>
   * lender
   * </pre>
   *
   * <code>.Lender lender_id = 4;</code>
   * @return The enum numeric value on the wire for lenderId.
   */
  int getLenderIdValue();
  /**
   * <pre>
   * lender
   * </pre>
   *
   * <code>.Lender lender_id = 4;</code>
   * @return The lenderId.
   */
  com.mservice.fs.onboarding.model.notipackage.protomodel.Lender getLenderId();

  /**
   * <pre>
   * rank
   * </pre>
   *
   * <code>int32 rank = 5;</code>
   * @return The rank.
   */
  int getRank();

  /**
   * <pre>
   * amount of the loan package
   * </pre>
   *
   * <code>int32 package_amount = 6;</code>
   * @return The packageAmount.
   */
  int getPackageAmount();

  /**
   * <pre>
   * Package status
   * </pre>
   *
   * <code>string package_status = 7;</code>
   * @return The packageStatus.
   */
  java.lang.String getPackageStatus();
  /**
   * <pre>
   * Package status
   * </pre>
   *
   * <code>string package_status = 7;</code>
   * @return The bytes for packageStatus.
   */
  com.google.protobuf.ByteString
      getPackageStatusBytes();

  /**
   * <pre>
   * Package type
   * </pre>
   *
   * <code>string package_type = 8;</code>
   * @return The packageType.
   */
  java.lang.String getPackageType();
  /**
   * <pre>
   * Package type
   * </pre>
   *
   * <code>string package_type = 8;</code>
   * @return The bytes for packageType.
   */
  com.google.protobuf.ByteString
      getPackageTypeBytes();

  /**
   * <pre>
   * Package classification (ex: ALL, OLD_UP_TO_50M, KYB_UP_TO_70M)
   * </pre>
   *
   * <code>string classification = 9;</code>
   * @return The classification.
   */
  java.lang.String getClassification();
  /**
   * <pre>
   * Package classification (ex: ALL, OLD_UP_TO_50M, KYB_UP_TO_70M)
   * </pre>
   *
   * <code>string classification = 9;</code>
   * @return The bytes for classification.
   */
  com.google.protobuf.ByteString
      getClassificationBytes();

  /**
   * <pre>
   * valid duration for a loan package
   * </pre>
   *
   * <code>int64 tenor = 10;</code>
   * @return The tenor.
   */
  long getTenor();

  /**
   * <pre>
   * the interest rate for on-time payment
   * </pre>
   *
   * <code>double interest_rate = 11;</code>
   * @return The interestRate.
   */
  double getInterestRate();

  /**
   * <pre>
   * interest amount
   * </pre>
   *
   * <code>float interest_amount = 12;</code>
   * @return The interestAmount.
   */
  float getInterestAmount();

  /**
   * <pre>
   * amount VND disbursed for users after subtracting all pre-collected fees
   * </pre>
   *
   * <code>float disbursed_amount = 13;</code>
   * @return The disbursedAmount.
   */
  float getDisbursedAmount();

  /**
   * <pre>
   * fixed payment amount VND needed to pay for each period
   * </pre>
   *
   * <code>float payment_amount = 14;</code>
   * @return The paymentAmount.
   */
  float getPaymentAmount();

  /**
   * <pre>
   * minimum loan amount
   * </pre>
   *
   * <code>float min_loan_amount = 15;</code>
   * @return The minLoanAmount.
   */
  float getMinLoanAmount();

  /**
   * <pre>
   * maximum loan amount
   * </pre>
   *
   * <code>float max_loan_amount = 16;</code>
   * @return The maxLoanAmount.
   */
  float getMaxLoanAmount();

  /**
   * <pre>
   * the fee for using the service
   * </pre>
   *
   * <code>float service_fee = 17;</code>
   * @return The serviceFee.
   */
  float getServiceFee();

  /**
   * <pre>
   * the collection cost for collecting debt
   * </pre>
   *
   * <code>float collection_fee = 18;</code>
   * @return The collectionFee.
   */
  float getCollectionFee();

  /**
   * <pre>
   * the fee of amount disbursed
   * </pre>
   *
   * <code>float disbursed_fee = 19;</code>
   * @return The disbursedFee.
   */
  float getDisbursedFee();

  /**
   * <pre>
   * interest rate for late payment
   * </pre>
   *
   * <code>double late_interest_rate = 20;</code>
   * @return The lateInterestRate.
   */
  double getLateInterestRate();

  /**
   * <pre>
   * penalty late fee
   * </pre>
   *
   * <code>float late_fee = 21;</code>
   * @return The lateFee.
   */
  float getLateFee();

  /**
   * <pre>
   * Equated Monthly Installment
   * </pre>
   *
   * <code>float emi = 22;</code>
   * @return The emi.
   */
  float getEmi();
}
