// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: get_offer_package.proto

package com.mservice.fs.onboarding.model.notipackage.protomodel;

/**
 * <pre>
 * type of product
 * </pre>
 *
 * Protobuf enum {@code ProductGroup}
 */
public enum ProductGroup
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOWN_PRODUCT_GROUP = 0;</code>
   */
  UNKNOWN_PRODUCT_GROUP(0),
  /**
   * <code>CASH_LOAN = 1;</code>
   */
  CASH_LOAN(1),
  /**
   * <code>PAYLATER = 2;</code>
   */
  PAYLATER(2),
  /**
   * <code>OVER_DRAFT = 3;</code>
   */
  OVER_DRAFT(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNKNOWN_PRODUCT_GROUP = 0;</code>
   */
  public static final int UNKNOWN_PRODUCT_GROUP_VALUE = 0;
  /**
   * <code>CASH_LOAN = 1;</code>
   */
  public static final int CASH_LOAN_VALUE = 1;
  /**
   * <code>PAYLATER = 2;</code>
   */
  public static final int PAYLATER_VALUE = 2;
  /**
   * <code>OVER_DRAFT = 3;</code>
   */
  public static final int OVER_DRAFT_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ProductGroup valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ProductGroup forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN_PRODUCT_GROUP;
      case 1: return CASH_LOAN;
      case 2: return PAYLATER;
      case 3: return OVER_DRAFT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ProductGroup>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ProductGroup> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ProductGroup>() {
          public ProductGroup findValueByNumber(int number) {
            return ProductGroup.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.mservice.fs.onboarding.model.notipackage.protomodel.GetOfferPackage.getDescriptor().getEnumTypes().get(5);
  }

  private static final ProductGroup[] VALUES = values();

  public static ProductGroup valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ProductGroup(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ProductGroup)
}

