// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetOfferPackageResponse

package com.mservice.fs.onboarding.model.notipackage.protomodel;

/**
 * Protobuf enum {@code ResponseMessage}
 */
public enum ResponseMessage
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOWN_MESSAGE = 0;</code>
   */
  UNKNOWN_MESSAGE(0),
  /**
   * <code>SUCCESS_RESPONSE = 1;</code>
   */
  SUCCESS_RESPONSE(1),
  /**
   * <code>INFO_NOT_FOUND = 2;</code>
   */
  INFO_NOT_FOUND(2),
  /**
   * <code>ERROR_RESPONSE = 3;</code>
   */
  ERROR_RESPONSE(3),
  /**
   * <code>SUCCESS_EXT = 4;</code>
   */
  SUCCESS_EXT(4),
  /**
   * <code>ERROR_EXT = 5;</code>
   */
  ERROR_EXT(5),
  /**
   * <code>TIME_OUT_EXT = 6;</code>
   */
  TIME_OUT_EXT(6),
  /**
   * <code>TIME_OUT_INT = 7;</code>
   */
  TIME_OUT_INT(7),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNKNOWN_MESSAGE = 0;</code>
   */
  public static final int UNKNOWN_MESSAGE_VALUE = 0;
  /**
   * <code>SUCCESS_RESPONSE = 1;</code>
   */
  public static final int SUCCESS_RESPONSE_VALUE = 1;
  /**
   * <code>INFO_NOT_FOUND = 2;</code>
   */
  public static final int INFO_NOT_FOUND_VALUE = 2;
  /**
   * <code>ERROR_RESPONSE = 3;</code>
   */
  public static final int ERROR_RESPONSE_VALUE = 3;
  /**
   * <code>SUCCESS_EXT = 4;</code>
   */
  public static final int SUCCESS_EXT_VALUE = 4;
  /**
   * <code>ERROR_EXT = 5;</code>
   */
  public static final int ERROR_EXT_VALUE = 5;
  /**
   * <code>TIME_OUT_EXT = 6;</code>
   */
  public static final int TIME_OUT_EXT_VALUE = 6;
  /**
   * <code>TIME_OUT_INT = 7;</code>
   */
  public static final int TIME_OUT_INT_VALUE = 7;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static ResponseMessage valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ResponseMessage forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN_MESSAGE;
      case 1: return SUCCESS_RESPONSE;
      case 2: return INFO_NOT_FOUND;
      case 3: return ERROR_RESPONSE;
      case 4: return SUCCESS_EXT;
      case 5: return ERROR_EXT;
      case 6: return TIME_OUT_EXT;
      case 7: return TIME_OUT_INT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ResponseMessage>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ResponseMessage> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ResponseMessage>() {
          public ResponseMessage findValueByNumber(int number) {
            return ResponseMessage.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return GetOfferPackageResponseOuterClass.getDescriptor().getEnumTypes().get(2);
  }

  private static final ResponseMessage[] VALUES = values();

  public static ResponseMessage valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ResponseMessage(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ResponseMessage)
}

