// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: get_offer_package.proto

package com.mservice.fs.onboarding.model.notipackage.protomodel;

/**
 * Protobuf enum {@code SegmentUser}
 */
public enum SegmentUser
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOWN_LOAN_SEGMENT_TYPE = 0;</code>
   */
  UNKNOWN_LOAN_SEGMENT_TYPE(0),
  /**
   * <code>NEW = 1;</code>
   */
  NEW(1),
  /**
   * <code>REPEATED = 2;</code>
   */
  REPEATED(2),
  /**
   * <code>QUICK_ACTIVATION = 3;</code>
   */
  QUICK_ACTIVATION(3),
  /**
   * <code>FAST_MONEY_PILOT_EXP = 4;</code>
   */
  FAST_MONEY_PILOT_EXP(4),
  /**
   * <code>BNPL_EXP_RULE = 5;</code>
   */
  BNPL_EXP_RULE(5),
  /**
   * <code>NEWTON_EXP_RULE = 6;</code>
   */
  NEWTON_EXP_RULE(6),
  /**
   * <code>NEWTON_FORCE_MANUAL_REVIEW = 7;</code>
   */
  NEWTON_FORCE_MANUAL_REVIEW(7),
  /**
   * <code>RELOAN = 8;</code>
   */
  RELOAN(8),
  /**
   * <code>EXP_RULE = 9;</code>
   */
  EXP_RULE(9),
  /**
   * <code>PILOT_GEN_Z = 10;</code>
   */
  PILOT_GEN_Z(10),
  /**
   * <code>HARRISON_EXP_RULE = 11;</code>
   */
  HARRISON_EXP_RULE(11),
  /**
   * <code>CHECK_KLP_PRE_SCORE = 12;</code>
   */
  CHECK_KLP_PRE_SCORE(12),
  /**
   * <code>THIN_FILE = 13;</code>
   */
  THIN_FILE(13),
  /**
   * <code>GENZ_STUDENT = 14;</code>
   */
  GENZ_STUDENT(14),
  /**
   * <code>HOME_CREDIT_ACL = 15;</code>
   */
  HOME_CREDIT_ACL(15),
  /**
   * <code>HOME_CREDIT_CLX = 16;</code>
   */
  HOME_CREDIT_CLX(16),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNKNOWN_LOAN_SEGMENT_TYPE = 0;</code>
   */
  public static final int UNKNOWN_LOAN_SEGMENT_TYPE_VALUE = 0;
  /**
   * <code>NEW = 1;</code>
   */
  public static final int NEW_VALUE = 1;
  /**
   * <code>REPEATED = 2;</code>
   */
  public static final int REPEATED_VALUE = 2;
  /**
   * <code>QUICK_ACTIVATION = 3;</code>
   */
  public static final int QUICK_ACTIVATION_VALUE = 3;
  /**
   * <code>FAST_MONEY_PILOT_EXP = 4;</code>
   */
  public static final int FAST_MONEY_PILOT_EXP_VALUE = 4;
  /**
   * <code>BNPL_EXP_RULE = 5;</code>
   */
  public static final int BNPL_EXP_RULE_VALUE = 5;
  /**
   * <code>NEWTON_EXP_RULE = 6;</code>
   */
  public static final int NEWTON_EXP_RULE_VALUE = 6;
  /**
   * <code>NEWTON_FORCE_MANUAL_REVIEW = 7;</code>
   */
  public static final int NEWTON_FORCE_MANUAL_REVIEW_VALUE = 7;
  /**
   * <code>RELOAN = 8;</code>
   */
  public static final int RELOAN_VALUE = 8;
  /**
   * <code>EXP_RULE = 9;</code>
   */
  public static final int EXP_RULE_VALUE = 9;
  /**
   * <code>PILOT_GEN_Z = 10;</code>
   */
  public static final int PILOT_GEN_Z_VALUE = 10;
  /**
   * <code>HARRISON_EXP_RULE = 11;</code>
   */
  public static final int HARRISON_EXP_RULE_VALUE = 11;
  /**
   * <code>CHECK_KLP_PRE_SCORE = 12;</code>
   */
  public static final int CHECK_KLP_PRE_SCORE_VALUE = 12;
  /**
   * <code>THIN_FILE = 13;</code>
   */
  public static final int THIN_FILE_VALUE = 13;
  /**
   * <code>GENZ_STUDENT = 14;</code>
   */
  public static final int GENZ_STUDENT_VALUE = 14;
  /**
   * <code>HOME_CREDIT_ACL = 15;</code>
   */
  public static final int HOME_CREDIT_ACL_VALUE = 15;
  /**
   * <code>HOME_CREDIT_CLX = 16;</code>
   */
  public static final int HOME_CREDIT_CLX_VALUE = 16;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static SegmentUser valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static SegmentUser forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN_LOAN_SEGMENT_TYPE;
      case 1: return NEW;
      case 2: return REPEATED;
      case 3: return QUICK_ACTIVATION;
      case 4: return FAST_MONEY_PILOT_EXP;
      case 5: return BNPL_EXP_RULE;
      case 6: return NEWTON_EXP_RULE;
      case 7: return NEWTON_FORCE_MANUAL_REVIEW;
      case 8: return RELOAN;
      case 9: return EXP_RULE;
      case 10: return PILOT_GEN_Z;
      case 11: return HARRISON_EXP_RULE;
      case 12: return CHECK_KLP_PRE_SCORE;
      case 13: return THIN_FILE;
      case 14: return GENZ_STUDENT;
      case 15: return HOME_CREDIT_ACL;
      case 16: return HOME_CREDIT_CLX;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<SegmentUser>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      SegmentUser> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<SegmentUser>() {
          public SegmentUser findValueByNumber(int number) {
            return SegmentUser.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.mservice.fs.onboarding.model.notipackage.protomodel.GetOfferPackage.getDescriptor().getEnumTypes().get(4);
  }

  private static final SegmentUser[] VALUES = values();

  public static SegmentUser valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private SegmentUser(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:SegmentUser)
}

