alter table ob_service_config add  ZERO_INTEREST number (1) default 0;
alter table OB_CONTRACT_CONFIG add APPLY_ZERO_INTEREST number(1) default 0;
update OB_SERVICE_CONFIG set ZERO_INTEREST = 1 where service_id = 'finance_lending_amber';
update ob_contract_config set apply_zero_interest = 1 where service_id = 'finance_lending_amber' and type = 'HDTD';


INSERT INTO FI_PACKAGES_INFO
(PRODUCT_GROUP, PACKAGE_NAME, PACKAGE_CODE, LOAN_AMOUNT, LOAN_TERM, LOAN_TERM_DURATION_UNIT, INTEREST_RATE, INTEREST_DURATION_UNIT, PAYMENT_PERIOD, INTEREST_AMOUNT, DISBURSED_AMOUNT, DISBURSED_FEE, COLLECTION_FEE, SERVICE_FEE, PAYMENT_AMOUNT, PAYMENT_EACH_PERIOD, LATE_INTEREST_RATE, MAX_PAYMENT_AMOUNT, MIN_PAYMENT_AMOUNT, ESIGN_FEE, MIN_PAYMENT_RATE, MIN_PAYMENT_DURATION_UNIT, LATE_FEE, LATE_INTEREST_DURATION_UNIT, EARLY_TERMINATION_FEE, PACKAGE_GROUP, LENDER_ID, DUE_DAY, PARTNERID, PARTNER_ID, PACKAGE_MAP_NAME, LENDER_NAME, MONTHLY_INTEREST_RATE, BEFORE_PAYMENT_AMOUNT, BEFORE_EMI)
VALUES('CASH_LOAN', 'fastmoney_612', 'MM612', 500000, 1, 'MONTH', 0, 'YEAR', 1, 0, 500000, 0, 20000, 0, 520000, 520000, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MMAAD_IR0', 'AMBER', NULL, NULL, 'evnfc', NULL, NULL, '0.00%', 545000, 545000);


INSERT INTO FI_PACKAGES_INFO
(PRODUCT_GROUP, PACKAGE_NAME, PACKAGE_CODE, LOAN_AMOUNT, LOAN_TERM, LOAN_TERM_DURATION_UNIT, INTEREST_RATE, INTEREST_DURATION_UNIT, PAYMENT_PERIOD, INTEREST_AMOUNT, DISBURSED_AMOUNT, DISBURSED_FEE, COLLECTION_FEE, SERVICE_FEE, PAYMENT_AMOUNT, PAYMENT_EACH_PERIOD, LATE_INTEREST_RATE, MAX_PAYMENT_AMOUNT, MIN_PAYMENT_AMOUNT, ESIGN_FEE, MIN_PAYMENT_RATE, MIN_PAYMENT_DURATION_UNIT, LATE_FEE, LATE_INTEREST_DURATION_UNIT, EARLY_TERMINATION_FEE, PACKAGE_GROUP, LENDER_ID, DUE_DAY, PARTNERID, PARTNER_ID, PACKAGE_MAP_NAME, LENDER_NAME, MONTHLY_INTEREST_RATE, BEFORE_PAYMENT_AMOUNT, BEFORE_EMI)
VALUES('CASH_LOAN', 'fastmoney_613', 'MM613', 1000000, 1, 'MONTH', 0, 'YEAR', 1, 0, 1000000, 0, 20000, 0, 1020000, 1020000, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MMAAD_IR0', 'AMBER', NULL, NULL, 'evnfc', NULL, NULL, '0.00%', 1070000, 1070000);


INSERT INTO FI_PACKAGES_INFO
(PRODUCT_GROUP, PACKAGE_NAME, PACKAGE_CODE, LOAN_AMOUNT, LOAN_TERM, LOAN_TERM_DURATION_UNIT, INTEREST_RATE, INTEREST_DURATION_UNIT, PAYMENT_PERIOD, INTEREST_AMOUNT, DISBURSED_AMOUNT, DISBURSED_FEE, COLLECTION_FEE, SERVICE_FEE, PAYMENT_AMOUNT, PAYMENT_EACH_PERIOD, LATE_INTEREST_RATE, MAX_PAYMENT_AMOUNT, MIN_PAYMENT_AMOUNT, ESIGN_FEE, MIN_PAYMENT_RATE, MIN_PAYMENT_DURATION_UNIT, LATE_FEE, LATE_INTEREST_DURATION_UNIT, EARLY_TERMINATION_FEE, PACKAGE_GROUP, LENDER_ID, DUE_DAY, PARTNERID, PARTNER_ID, PACKAGE_MAP_NAME, LENDER_NAME, MONTHLY_INTEREST_RATE, BEFORE_PAYMENT_AMOUNT, BEFORE_EMI)
VALUES('CASH_LOAN', 'fastmoney_614', 'MM614', 1500000, 1, 'MONTH', 0, 'YEAR', 1, 0, 1500000, 0, 20000, 0, 1520000, 1520000, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MMAAD_IR0', 'AMBER', NULL, NULL, 'evnfc', NULL, NULL, '0.00%', 1595000, 1595000);


INSERT INTO FI_PACKAGES_INFO
(PRODUCT_GROUP, PACKAGE_NAME, PACKAGE_CODE, LOAN_AMOUNT, LOAN_TERM, LOAN_TERM_DURATION_UNIT, INTEREST_RATE, INTEREST_DURATION_UNIT, PAYMENT_PERIOD, INTEREST_AMOUNT, DISBURSED_AMOUNT, DISBURSED_FEE, COLLECTION_FEE, SERVICE_FEE, PAYMENT_AMOUNT, PAYMENT_EACH_PERIOD, LATE_INTEREST_RATE, MAX_PAYMENT_AMOUNT, MIN_PAYMENT_AMOUNT, ESIGN_FEE, MIN_PAYMENT_RATE, MIN_PAYMENT_DURATION_UNIT, LATE_FEE, LATE_INTEREST_DURATION_UNIT, EARLY_TERMINATION_FEE, PACKAGE_GROUP, LENDER_ID, DUE_DAY, PARTNERID, PARTNER_ID, PACKAGE_MAP_NAME, LENDER_NAME, MONTHLY_INTEREST_RATE, BEFORE_PAYMENT_AMOUNT, BEFORE_EMI)
VALUES('CASH_LOAN', 'fastmoney_615', 'MM615', 2000000, 1, 'MONTH', 0, 'YEAR', 1, 0, 2000000, 0, 20000, 0, 2020000, 2020000, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MMAAD_IR0', 'AMBER', NULL, NULL, 'evnfc', NULL, NULL, '0.00%', 2120000, 2120000);


INSERT INTO FI_PACKAGES_INFO
(PRODUCT_GROUP, PACKAGE_NAME, PACKAGE_CODE, LOAN_AMOUNT, LOAN_TERM, LOAN_TERM_DURATION_UNIT, INTEREST_RATE, INTEREST_DURATION_UNIT, PAYMENT_PERIOD, INTEREST_AMOUNT, DISBURSED_AMOUNT, DISBURSED_FEE, COLLECTION_FEE, SERVICE_FEE, PAYMENT_AMOUNT, PAYMENT_EACH_PERIOD, LATE_INTEREST_RATE, MAX_PAYMENT_AMOUNT, MIN_PAYMENT_AMOUNT, ESIGN_FEE, MIN_PAYMENT_RATE, MIN_PAYMENT_DURATION_UNIT, LATE_FEE, LATE_INTEREST_DURATION_UNIT, EARLY_TERMINATION_FEE, PACKAGE_GROUP, LENDER_ID, DUE_DAY, PARTNERID, PARTNER_ID, PACKAGE_MAP_NAME, LENDER_NAME, MONTHLY_INTEREST_RATE, BEFORE_PAYMENT_AMOUNT, BEFORE_EMI)
VALUES('CASH_LOAN', 'fastmoney_616', 'MM616', 2500000, 1, 'MONTH', 0, 'YEAR', 1, 0, 2500000, 0, 20000, 0, 2520000, 2520000, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MMAAD_IR0', 'AMBER', NULL, NULL, 'evnfc', NULL, NULL, '0.00%', 2645000, 2645000);


INSERT INTO FI_PACKAGES_INFO
(PRODUCT_GROUP, PACKAGE_NAME, PACKAGE_CODE, LOAN_AMOUNT, LOAN_TERM, LOAN_TERM_DURATION_UNIT, INTEREST_RATE, INTEREST_DURATION_UNIT, PAYMENT_PERIOD, INTEREST_AMOUNT, DISBURSED_AMOUNT, DISBURSED_FEE, COLLECTION_FEE, SERVICE_FEE, PAYMENT_AMOUNT, PAYMENT_EACH_PERIOD, LATE_INTEREST_RATE, MAX_PAYMENT_AMOUNT, MIN_PAYMENT_AMOUNT, ESIGN_FEE, MIN_PAYMENT_RATE, MIN_PAYMENT_DURATION_UNIT, LATE_FEE, LATE_INTEREST_DURATION_UNIT, EARLY_TERMINATION_FEE, PACKAGE_GROUP, LENDER_ID, DUE_DAY, PARTNERID, PARTNER_ID, PACKAGE_MAP_NAME, LENDER_NAME, MONTHLY_INTEREST_RATE, BEFORE_PAYMENT_AMOUNT, BEFORE_EMI)
VALUES('CASH_LOAN', 'fastmoney_617', 'MM617', 3000000, 1, 'MONTH', 0, 'YEAR', 1, 0, 3000000, 0, 20000, 0, 3020000, 3020000, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MMAAD_IR0', 'AMBER', NULL, NULL, 'evnfc', NULL, NULL, '0.00%', 3170000, 3170000);


alter table ob_service_config add SCORE_SERVICE_ID_RISK varchar2(100);
alter table ob_service_config add SCORE_MSG_TYPE_RISK varchar2(100);
update ob_service_config set SCORE_SERVICE_ID_RISK = 'sof_loan_disbursement_fastmoney', SCORE_MSG_TYPE_RISK = 'FS_EVENT_FASTMONEY' where service_id = 'finance_lending_amber';

create table OB_MINI_APP_VERSION_CONFIG (
    SERVICE_ID VARCHAR2(100),
    PROCESS_NAME VARCHAR2(100),
    RESULT_CODE NUMBER,
    VERSION NUMBER
);

create table OB_TELCO_CONFIG (
    SERVICE_ID VARCHAR2(100),
    MAX_GENERATE_OTP_TIMES  NUMBER,
    MAX_VERIFY_OTP_TIMES    NUMBER,
    RESET_OTP_IN_MILLIS     NUMBER,
    VALID_OTP_IN_MILLIS     NUMBER
);

alter table FI_APPLICATION_INFO add TELCO number(1) default 0;
Insert into OB_RENDER_DATA (SERVICE_ID,PARTNER_ID,RESULT_CODE,RESULT_MESSAGE,IMAGE,TITLE,MESSAGE,RENDER_TYPE,PRIMARY,SECONDARY,BUTTON_DIRECTION,PRIMARY_CTA,SECONDARY_CTA,PROCESS_NAME,PARTNER_MAP_ID,TRACKING_PARAMS,NAVIGATION_TYPE) values ('finance_lending_amber',null,'1101',null,null,'Thông báo','Bạn đã yêu cầu OTP quá 3 lần. Vui lòng thử lại sau 24h nữa nhé.','POPUP','{"code":"GO_BACK","initCountDownInSeconds":0,"name":"Đã hiểu","trackingParams":{"name":"understand"}}',null,'ROW',null,null,'generate-otp-telco',null,'{"name":"otp_limit"}',null);
Insert into OB_RENDER_DATA (SERVICE_ID,PARTNER_ID,RESULT_CODE,RESULT_MESSAGE,IMAGE,TITLE,MESSAGE,RENDER_TYPE,PRIMARY,SECONDARY,BUTTON_DIRECTION,PRIMARY_CTA,SECONDARY_CTA,PROCESS_NAME,PARTNER_MAP_ID,TRACKING_PARAMS,NAVIGATION_TYPE) values ('finance_lending_amber',null,'1202',null,null,'Thông báo','Bạn đã nhập sai OTP quá 3 lần. Vui lòng thử lại sau 24h nữa nhé.','POPUP','{"code":"EXIT_APP","initCountDownInSeconds":0,"name":"Đã hiểu","trackingParams":{"name":"understand"}}',null,'ROW',null,null,'verify-otp-telco',null,'{"name":"otp_limit"}',null);

ALTER TABLE OB_PARTNER_CONFIG ADD APPLY_SCORE_AT_LOAN_DECIDER NUMBER(1,0) DEFAULT 0;
UPDATE OB_PARTNER_CONFIG SET APPLY_SCORE_AT_LOAN_DECIDER = '1' WHERE partner_id = 'ccm_vcb' and service_id = 'finance_creditcard_marketplace';

ALTER TABLE ob_service_config ADD STATUS_ALLOW_CANCEL_BY_LENDER VARCHAR2(500 BYTE);
UPDATE ob_service_config set STATUS_ALLOW_CANCEL_BY_LENDER = 'APPROVED_BY_LENDER,REVIEW_BY_LENDER,VERIFIED_OTP_SUCCESS,ACCEPTED_BY_LENDER,ACCEPTED_BY_MOMO,REJECTED_BY_LIMITED_GENERATED_OTP_EXCEED,REJECTED_BY_LIMITED_VERIFIED_OTP_EXCEED,VERIFIED_OTP_FAILED' where service_id = 'finance_lending_amber';

ALTER TABLE ob_service_config ADD STATUS_ALLOW_REJECT_BY_LENDER VARCHAR2(500 BYTE);
UPDATE ob_service_config set STATUS_ALLOW_REJECT_BY_LENDER = 'APPROVED_BY_LENDER,REVIEW_BY_LENDER,VERIFIED_OTP_SUCCESS,ACCEPTED_BY_LENDER,ACCEPTED_BY_MOMO,REJECTED_BY_LIMITED_GENERATED_OTP_EXCEED,REJECTED_BY_LIMITED_VERIFIED_OTP_EXCEED,VERIFIED_OTP_FAILED' where service_id = 'finance_lending_amber';

ALTER TABLE FI_PACKAGES_INFO ADD FLAT_MONTHLY_INTEREST_RATE NUMBER;

INSERT INTO OB_ACTION_CONFIG (SERVICE_ID, ACTION_ID, PROCESS_NAME) VALUES ('finance_lending_amber', 'SEND_PLATFORM_LOAN_ACTION', 'final-submit')
INSERT INTO OB_ACTION_CONFIG (SERVICE_ID, ACTION_ID, PROCESS_NAME) VALUES ('finance_lending_amber', 'SEND_PLATFORM_LOAN_ACTION', 'confirm-face-matching')
INSERT INTO OB_ACTION_FIELD (NAME, ACT_CONFIG_ID, ACTION_NAME, PROCESS_NAME, SERVICE_ID, TYPE) VALUES ('PENDING_APPLICATION', (SELECT ID FROM OB_ACTION_CONFIG where service_id = 'finance_lending_amber' and action_id = 'SEND_PLATFORM_LOAN_ACTION' and process_name = 'final-submit'), 'SEND_PLATFORM_LOAN_ACTION', 'final-submit', 'finance_lending_amber', 'CHECK_CONTAINS')
INSERT INTO OB_ACTION_FIELD (NAME, ACT_CONFIG_ID, ACTION_NAME, PROCESS_NAME, SERVICE_ID, TYPE) VALUES ('PENDING_APPLICATION', (SELECT ID FROM OB_ACTION_CONFIG where service_id = 'finance_lending_amber' and action_id = 'SEND_PLATFORM_LOAN_ACTION' and process_name = 'confirm-face-matching'), 'SEND_PLATFORM_LOAN_ACTION', 'confirm-face-matching', 'finance_lending_amber', 'CHECK_CONTAINS')
INSERT INTO OB_LOAN_DECIDER_CONFIG (ACTION_NAME, RESULT_CODE, REDIRECT_PROCESS_NAME, TYPE) VALUES ('PENDING_APPLICATION', '20013', 'final-submit', 'LOAN_DECIDER')

INSERT INTO OB_RENDER_DATA (SERVICE_ID, RESULT_CODE, TITLE, MESSAGE, RENDER_TYPE, PRIMARY, SECONDARY, BUTTON_DIRECTION, PRIMARY_CTA, SECONDARY_CTA, PROCESS_NAME, TRACKING_PARAMS) VALUES ('finance_lending_amber', '20013', 'Bạn có thể đang bị lừa đảo!', 'Vay Nhanh nghi ngờ bạn đang thực hiện vay theo hướng dẫn của đối tượng lừa đảo. Bạn vui lòng gọi tổng đài nhanh 1900 99 66 65 hoạt động từ 8:00 – 22:00 để được hỗ trợ xử lý nếu bị lừa đảo và mở lại hồ sơ vay nếu bạn không bị thao túng.', 'POPUP', '{"code":"CALL_PHONE","initCountDownInSeconds":0,"name":"Gọi CSKH","trackingParams":{"name":"call_cs"},"data":{"phoneNumber":"1900996665"}}', '{"code":"CLOSE_POPUP","initCountDownInSeconds":0,"name":"Đóng","trackingParams":{"name":"close"}}', 'ROW', '{"code":"CALL_PHONE","initCountDownInSeconds":0,"name":"Gọi CSKH","trackingParams":{"name":"call_cs"},"data":{"phoneNumber":"0908123123"}}', '{"code":"CLOSE_POPUP","initCountDownInSeconds":0,"name":"Đóng","trackingParams":{"name":"close"}}', 'final-submit', '{"name":"anti_scam_callcs"}')



