package com.mservice.fs.onboarding.model.common.config;

/**
 * @author hoang.thai
 * on 12/3/2023
 */
public enum Action {

    CHECK_KNOCK_OUT_RULE,
    CHECK_LOAN_DECIDER,
    GET_PACKAGE,
    CHECK_USER_PROFILE,
    CHECK_DE_DUP_ONBOARDING,
    CHECK_DE_DUP_PARTNER,
    CROSS_CHECK_FACE_MATCHING,
    SEND_ADAPTER_LISTENER,
    SEND_PLATFORM_LISTENER,
    GET_USER_PROFILE,
    GET_SOCIAL_SELLER_DATA,
    GET_PAYMENT_INFO,
    EVENT_TO_AI,
    NOTI_USER,
    BANNED_BY_PARTNER,
    VERIFY_FACE_MATCHING,
    REMIND_PENDING_FORM,
    SEND_ADAPTER_SUBMIT,
    SEND_USER_CONSENT,
    CHECK_OUT_WHITE_LIST,
    VALIDATE_PACKAGE,
    CLEAR_PENDING_FORM_BY_PARTNER,
    UPDATE_CACHE_TIME_WHEN_BANNED,
    UPDATE_WHEN_FAIL,
    SEND_PLATFORM_LOAN_ACTION,
    SEND_PLATFORM_TASK
    ;

}
