package com.mservice.fs.onboarding.enums;

public enum AIMessageType {
    UNKNOWN_LOG,
    START_SCREEN_LOG,
    MID_SCREEN_LOG,
    SUMMARY_SCREEN_LOG,
    OPT_LOG_REQUEST,
    OPT_LOG_RESPONSE,
    LOAN_FINAL_RESULT_LOG,
    LOAN_PARTNER_RESULT_LOG,
    LOAN_REPAYMENT_LOG,
    LOAN_DISBURSEMENT_LOG,
    TOTAL_PAYMENT_INFO_EVENT,
    PAYMENT_INFO_EVENT;
}
